### ISSUE TITLE
Discover heatpump

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#1]
Current state: **working**
Currently using the (or)
- Siemens mac address range: **000E8C***
- Fujitsu mac address range: **001999***
- Loewe Opta GmbH mac address range: **000982***
- hostname: **wp-novelan**
After the dhcp lookup the broadcast discovery (AIT magic brodcast packet) is executed. If the ip address matches both discoveries the heatpump can be configured.

TODO:
- [x] Check the mac address range with other heatpumps in real live.
- [x] Check or detect other heatpump hostnames.

**Comment by macrojames** [comment]
![image](https://user-images.githubusercontent.com/482151/139841304-d747361d-80c1-4751-bc07-7771b0ec657a.png)
@BenPru I tried.

**Comment by BenPru** [comment]
I think this can be closed.
