### ISSUE TITLE
Question: Where to find the configuration UI

### ISSUE THREAD

**Issue by augi** [BenPru/luxtronik#10]
Hello, thank you for you effort with this integration!

I've just downloaded it via HACS but I don't know where to find the UI for configuration (as shown in the README). So I'm not able to configure IP address and port of my heatpump 😢

**Comment by BenPru** [comment]
The autodiscover doesn't work in your case.
Please give feedback with the first six chars of your luxtronik heatpump mac address and hostname.

You can add the heatpump manually:
1. Settings -> Devices & Services -> Add Integration
2. Luxtronik
3. Follow the config flow and fill in hostname or ip and so on.

**Comment by augi** [comment]
Hi, thank you very much! 👍  I didn't know that I have to add also the new device manually, so #9 would help 🙏 

MAC address of my heatpump starts with `04-d1-6e`. Hope it helps 🙏

**Comment by BenPru** [comment]
> Hi, thank you very much! +1 I didn't know that I have to add also the new device manually, so #9 would help pray
> 
> MAC address of my heatpump starts with `04-d1-6e`. I'm not aware of any hostname of my heatpump (I access it via IP address). Hope it helps pray

Thanks. I have added the range to autodiscover this mac range.
Can you please tell me your manufacturer and model?

**Comment by augi** [comment]
Sure, it is `Alpha Innotec LWD 90A-HMD1`.
