### ISSUE TITLE
Icon not available for "update.luxtronik2_firmware"

### ISSUE THREAD

**Issue by Jeanlucpica** [BenPru/luxtronik#102]
Hello,
the sensor "Luxtronik Firmware" shows without an icon in my dashboard. It is configured to use "mdi:package-up" but I don't understand why it is not used. Is this a general error or a problem on my side?

<img width="360" alt="image" src="https://user-images.githubusercontent.com/65825096/236664933-bf83d33d-207f-4af0-9f09-1e027e96f19a.png">

**Comment by BenPru** [comment]
Sometimes it works, sometimes not...
I don't know why.

**Comment by AJediIAm** [comment]
Home Assistant requires the icons to be added to the brands repository with the exact name of the integration.
Luxtronik already exists. I submitted a pull request to copy the icons to Luxtronik2 so this integration also works.

**Comment by AJediIAm** [comment]
Fixed by: https://github.com/home-assistant/brands/pull/4662

Issue can be closed.

**Comment by BenPru** [comment]
Thanks
