### ISSUE TITLE
Question: sensor.luxtronik2_status_line_3 working again?

### ISSUE THREAD

**Issue by remyderuysscher** [BenPru/luxtronik#105]
Hi, is sensor.luxtronik2_status_line_3 working again in V3.88? Since I'm running V3,85 now and not willing to upgrade if this status line is not working.  There are no changelogs of the firmware so I'm anxious to update a working heatpump.

**Comment by BenPru** [comment]
I have no problems with L3.
Please try pre-release [2023.9.10](https://github.com/BenPru/luxtronik/releases/tag/2023.9.10)
