### ISSUE TITLE
No Watt or Kilowatt sensors after Luxtronik 3.88.1 update

### ISSUE THREAD

**Issue by idominiki** [BenPru/luxtronik#107]
Hi @BenPru 

after I updated my heat pump to V3.88.1, I can't get the Watt or Kilowatt sensors anymore.

<img width="480" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/cc134888-ff9d-4dd7-8716-3d7fee829405">

**Comment by BenPru** [comment]
Please try the pre-release [2023.9.10](https://github.com/BenPru/luxtronik/releases/tag/2023.9.10)
