### ISSUE TITLE
YAML code of README examples

### ISSUE THREAD

**Issue by WhistleMaster** [BenPru/luxtronik#11]
Hi !

Thanks for the work ! Would it be possible to share the YAML of the examples on your README page ?

Regards,

WM

**Comment by BenPru** [comment]
Here is the yaml code for the last screenshot:

`
  - icon: mdi:hvac
    path: hwr
    title: Heizung
    panel: false
    visible:
      - user: 8e1aca1ee72847fe891f60ece9f36b6d
    badges: []
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.heating_season_or_water
            state: 'on'
        card:
          type: vertical-stack
          cards:
            - type: entity
              entity: sensor.luxtronik_status
              state_color: true
              theme: ben
              name: Heizung
            - type: markdown
              content: '{{ state_attr(''sensor.luxtronik_status'', ''status_text'') }}'
              theme: ben
      - type: grid
        cards:
          - type: thermostat
            entity: climate.luxtronik_heating
          - type: thermostat
            entity: climate.luxtronik_domestic_water
          - type: entities
            entities:
              - entity: switch.luxtronik_heating
                name: Heizung
                secondary_info: last-updated
              - entity: number.luxtronik_heating_temperature_correction
                name: Korrektur
              - type: divider
              - entity: sensor.luxtronik_flow_in_temperature
                name: Vorlauf
              - entity: sensor.luxtronik_flow_out_temperature
                name: Rücklauf
              - entity: sensor.luxtronik_flow_out_temperature_target
                name: Soll
                secondary_info: last-changed
            state_color: true
          - type: vertical-stack
            cards:
              - type: entities
                entities:
                  - entity: switch.luxtronik_domestic_water
                    name: Brauchwasser
                    secondary_info: last-updated
                  - entity: number.luxtronik_domestic_water_target_temperature
                    name: Soll
                  - type: divider
                  - entity: binary_sensor.luxtronik_solar_pump
                    name: Solar
                    secondary_info: last-updated
                state_color: true
              - type: gauge
                entity: sensor.luxtronik_domestic_water_temperature
                min: 38
                max: 50
                name: Brauchwasser
                needle: true
                severity:
                  green: 40
                  yellow: 43
                  red: 48
        columns: 2
      - type: entities
        entities:
          - entity: sensor.luxtronik_status_line_1
            secondary_info: last-changed
          - entity: sensor.luxtronik_status_line_2
            secondary_info: last-changed
          - entity: sensor.luxtronik_status_line_3
            secondary_info: last-changed
          - entity: sensor.luxtronik_outdoor_temperature
          - entity: sensor.luxtronik_heat_source_input_temperature
        state_color: true
      - entities:
          - entity: binary_sensor.luxtronik_id_web_vboout
            secondary_info: last-changed
          - entity: input_number.heating_temperatur_day
            name: Tag +/-
          - entity: input_number.heating_temperatur_night
            name: Nacht +/-
          - entity: input_number.heating_temperatur_on
            name: An +/-
        type: entities
        state_color: true
        show_header_toggle: false
      - type: markdown
        content: >
          {% macro calc_day_val(day_value) %}{{ (day_value | int(default=0) /
          3600) | int(default=0) }}:{{ ((day_value | int(default=0) / 60) % 60)
          | int(default=0) }}{% endmacro %}

          {% macro getVal(history, calc_day, var_name, factor) %}{% set
          result_value = (((state_attr(var_name, 'last_period') if history else
          states(var_name)) | float(default=0)) * factor) | round(1, method

          ="round-to-even", default=0) %}{{ calc_day_val(result_value) if
          calc_day else result_value}}{% endmacro %}

          {% macro build_line(history, calc_day, icon_name, line_name, var_name,
          sum_name, unit, factor) %}| <ha-icon icon="{{ icon_name }}"></ha-icon>
          | {{ line_name }} | **{{ getVal(history, calc_day, var_name +
          '_daily', factor) }}** | {{ getVal(history, calc_day, var_name +
          '_weekly', factor)  }} | {{ getVal(history, calc_day, var_name +
          '_monthly', factor) }} | {{ getVal(history, calc_day, var_name +
          '_yearly', factor) }} |  {{ '' if history else (((states(sum_name) |
          int(default=0)) if calc_day else states(sum_name)) | int(default=0))
          }} {{ unit }} | {% endmacro %}

          {% macro build_row(icon_name, calc_day, line_name, var_name, sum_name,
          unit, factor=1) %}{{ build_line(False, calc_day, icon_name, line_name,
          var_name, sum_name, unit, factor) }}

          {{ build_line(True, calc_day, '', 'Vorher', var_name, sum_name, unit,
          factor) }}{% endmacro %}


          | | | Tag | Woche | Monat | Jahr | Gesamt | |

          |----|----|------------------------:|---------------------------------:|---:|---:|---:|--|

          {{ build_row('mdi:pulse', False, 'Impulse', 'sensor.heizung_impulse',
          'sensor.luxtronik_compressor_impulses', '') }}

          {{ build_row('mdi:timer-sand', True, 'Gesamt',
          'sensor.heizung_betriebsstunden_gesamt',
          'sensor.luxtronik_operation_hours', 'h') }}

          {{ build_row('mdi:timer-sand', True, 'Heizung',
          'sensor.heizung_betriebsstunden',
          'sensor.luxtronik_operation_hours_heating', 'h') }}

          {{ build_row('mdi:timer-sand', True, 'Wasser',
          'sensor.heizung_betriebsstunden_brauchwasser',
          'sensor.luxtronik_operation_hours_domestic_water', 'h') }}

          {{ build_row('mdi:timer-sand', True, 'Solar',
          'sensor.heizung_betriebsstunden_solar',
          'sensor.luxtronik_operation_hours_solar', 'h') }}

          {{ build_row('mdi:lightning-bolt-circle', False, 'Heizung',
          'sensor.heizung_warmemenge', 'sensor.luxtronik_heat_amount_heating',
          'kWh') }}

          {{ build_row('mdi:lightning-bolt-circle', False, 'Wasser',
          'sensor.heizung_warmemenge_brauchwasser',
          'sensor.luxtronik_heat_amount_domestic_water', 'kWh') }}

          {{ build_row('mdi:fan', False, 'Lüftung', 'sensor.lftung',
          'sensor.lftung_energy_total', 'kWh', 0.001) }}

          {{ build_row('mdi:air-purifier', False, 'Lftg Heiz.',
          'sensor.air_preheater', 'sensor.steckdose3_energy_total', 'kWh',
          0.001) }}
      - type: conditional
        conditions:
          - entity: binary_sensor.heating_season
            state: 'off'
        card:
          cards:
            - entity: sensor.luxtronik_domestic_water_temperature
              max: 75
              min: 40
              severity:
                green: 40
                red: 65
                yellow: 55
              type: gauge
              needle: true
              name: Brauchwasser
            - entities:
                - entity: binary_sensor.luxtronik_solar_pump
                  name: Solar
                - entity: sensor.luxtronik_solar_collector_temperature
                  name: Kollektor
                - entity: sensor.luxtronik_solar_buffer_temperature
                  name: Puffer
              type: entities
              state_color: true
              show_header_toggle: false
          type: horizontal-stack
      - type: conditional
        conditions:
          - entity: binary_sensor.heating_season
            state: onn
        card:
          cards:
            - entity: sensor.luxtronik_domestic_water_temperature
              min: 38
              severity:
                green: 40
                red: 48
                yellow: 43
              type: gauge
              max: 50
              needle: true
              name: Brauchwasser
            - entities:
                - entity: sensor.luxtronik_flow_in_temperature
                  name: Vorlauf
                - entity: sensor.luxtronik_flow_out_temperature
                  name: Rücklauf
                - entity: sensor.luxtronik_flow_out_temperature_target
                  name: Soll
                  secondary_info: last-changed
              type: entities
              state_color: true
          type: horizontal-stack
`

**Comment by WhistleMaster** [comment]
Thanks !
