### ISSUE TITLE
Integration in home assist

### ISSUE THREAD

**Issue by dinkelnaar** [BenPru/luxtronik#110]
Hello, i tried to follow instructions to integrate in homeassist.
But without succes.
If i read homeassist manual it says the following :

Repository configuration
Each repository is required to contain repository.yaml at the root in the git repository.

Quite new to homeassist and github so tried different things. Seems if i put this file in my own git i can add this as repo. But i cannot use it.

Who can help?

**Comment by AJediIAm** [comment]
Try posting your questions on the home assistant forum. This is not the right place for help.
Tip: use HACS

**Comment by BenPru** [comment]
Should be fixed with the pre-release [2023.9.10](https://github.com/BenPru/luxtronik/releases/tag/2023.9.10)
Thanks four your support.
