### ISSUE TITLE
homeaHome Assistant 2023.8.1 /since last HA update i have a bunch of error messages here

### ISSUE THREAD

**Issue by kotana** [BenPru/luxtronik#112]
![image](https://github.com/Bouni/luxtronik/assets/760382/d12a18f6-2103-4c1d-8b97-b2f9c9453c9a)
![image](https://github.com/Bouni/luxtronik/assets/760382/723fe704-74de-4e6d-b003-f18ced1986c2)
![image](https://github.com/Bouni/luxtronik/assets/760382/6b35cf5b-8496-4690-be60-0d74b1b4ed7a)
![image](https://github.com/Bouni/luxtronik/assets/760382/9f49f591-f727-45fb-875d-ead4ea8e5377)
![image](https://github.com/Bouni/luxtronik/assets/760382/584c9b51-62ab-48b6-a439-770c93a7ccfc)
![image](https://github.com/Bouni/luxtronik/assets/760382/7efd9f4b-2938-4cba-87bd-8d4eb687e5aa)
![image](https://github.com/Bouni/luxtronik/assets/760382/99aa6a18-42dc-4f88-ac4b-18c4d5a3a993)
![image](https://github.com/BenPru/luxtronik/assets/760382/9c4d4fd7-b2c3-4236-a9c9-7d725fe6974a)

**Comment by Crashman1983** [comment]
confirmed working after manual update, cannot see any differences in behavior for the first moment. No error Messages in Log
