### ISSUE TITLE
Auto detect devices - Novelan

### ISSUE THREAD

**Issue by tdia6** [BenPru/luxtronik#113]
Hello @BenPru,

i am new to home assistant, so it happend that i had to reinstall my server and home assistant.

At the first time trying your luxtronic it detected 3 devices and many entities.
But with my new installation there are only 84 entities... is there a chance to get also the devices?
the first 6 letters of the mac adress are 04:D1:6E - heatpump is a novelan licv 8 with the newest update.

thank you,
greets 
Patrick

**Comment by scaronni** [comment]
It's currently not working with home assistant 2023.8, it does not report any entity. Probably related to https://github.com/BenPru/luxtronik/issues/112.

**Comment by BenPru** [comment]
Should be fixed with the pre-release [2023.9.10](https://github.com/BenPru/luxtronik/releases/tag/2023.9.10)
Thanks four your support.
