### ISSUE TITLE
HA 2023.9b2: All entities missing

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#115]
Since HA 2023.9b1 Luxtronic stopped working. No entities available anymore .

**Comment by Crashman1983** [comment]
luxtronik2: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.2.176/', 'default_manufacturer': 'Alpha Innotec', 'default_model': '', 'default_name': 'Wärmepumpe', 'identifiers': {('luxtronik2', '310312_0495_heatpump')}, 'manufacturer': None, 'model': None, 'name': 'Wärmepumpe [310312-0495](tel:310312-0495)', 'suggested_area': 'Utility room', 'sw_version': 'V3.88.0'} for 'luxtronik2' config entry: device info needs to either describe a device, link to existing device or provide extra information.Hi

**Comment by rhammen** [comment]
Looks identical to #112 
I made changes to the luxtronik code locally that should fix these errors (they do fix the problems for me; I am using HA 2023.8.4).
I have submitted a pull-request #114 to integrate the changes in the main code.
--> Let's hope BenPru can integrate this change soon.

**Comment by rcreate** [comment]
I have the same problem. @BenPru can you please check the PR to solve this? It would be very nice 👍

**Comment by dickdahm** [comment]
Same here since update to Home Assistant 2023.9.0.
Hoped cold shower could fix it, but nope it´s not, just brutally awake now :)

**Comment by dickdahm** [comment]
> I have the same problem. I solved it by using main branch. @BenPru hopefully a new release is coming soon 😉

Can you maybe describe how exactly you did that?

**Comment by rcreate** [comment]
In HACS tap the three dots -> Redownload -> beta releases: yes -> choose main from dropdown -> download

**Comment by dickdahm** [comment]
> > Can you maybe describe how exactly you did that?
> 
> In HACS tap the three dots -> Redownload -> beta releases: yes -> choose main from dropdown -> download

In the meantime I fixed this by replacing __init__.py with the fixed version from rhammen. Can I break something now or after future updates by doing this?

**Comment by BenPru** [comment]
Should be fixed with the pre-release [2023.9.10](https://github.com/BenPru/luxtronik/releases/tag/2023.9.10)
Thanks four your support.
