### ISSUE TITLE
RuntimeWarning: coroutine 'LuxtronikThermostat._async_control_heating

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#116]
Don't know what that means in practice....

Logger: py.warnings
Source: custom_components/luxtronik2/climate.py:254 
Integration: Luxtronik 
First occurred: 07:54:14 (1 occurrences) 
Last logged: 07:54:14

/config/custom_components/luxtronik2/climate.py:254: RuntimeWarning: coroutine 'LuxtronikThermostat._async_control_heating' was never awaited self._async_control_heating()

**Comment by BenPru** [comment]
See the issue #75.
