### ISSUE TITLE
I can not add additional parameters??

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#123]
What ist wrong guys ?

sensor:
  - platform: luxtronik2
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TVL
      - id: calculations.ID_WEB_Temperatur_TVL
        friendly_name: Temperatur Vorlauf
        icon: mdi:thermometer
      - group: calculations
        id: ID_WEB_WMZ_Durchfluss
      - id: calculation.ID_WEB_WMZ_Durchfluss
        friendly_name: WMZ_Durchfluss
      - group: calculations
        id: ID_WEB_Durchfluss_WQ
      - id: calculation.ID_WEB_Durchfluss_WQ
        friendly_name: Durchfluss_WQ

**Comment by BenPru** [comment]
Which HA and luxtronik integration version habe you installed?
Please provide an integration diag file as attachment in this ticket.

**Comment by colognebroker** [comment]
[config_entry-luxtronik2-0f26c9a1c64546377e3ad50d2ff8cab5.json (1).txt](https://github.com/BenPru/luxtronik/files/12612385/config_entry-luxtronik2-0f26c9a1c64546377e3ad50d2ff8cab5.json.1.txt)

**Comment by BenPru** [comment]
This is normal and no bug.
Please notice that the Alpha-Core-Preview no more support yaml configs! You can use https://github.com/Bouni/luxtronik parallel for yaml configs.

**Comment by BenPru** [comment]
See
sensor.*_flow_in_temperature
ID_WEB_Temperatur_TVL

**Comment by colognebroker** [comment]
yes thank you
but when i update to new core [2023.9.2]
luxtronik2 shows no devices anymore ?

**Comment by colognebroker** [comment]
with with luxtronik2 [2023.04.30](https://github.com/BenPru/luxtronik/releases/tag/2023.04.30)
should i downgrade to 2023.03.24 ??

**Comment by BenPru** [comment]
Please try [2023.9.19-Alpha-Core-Preview](https://github.com/BenPru/luxtronik/releases/tag/2023.9.19-Alpha-Core-Preview)
