### ISSUE TITLE
outdoor_temperature read once and no upcoming updates later

### ISSUE THREAD

**Issue by qubabos** [BenPru/luxtronik#125]
With 2023.9.12-Alpha-Core-Preview the sensor.luxtronik2_outdoor_temperature update once after integration setup, and the no other temperature update since then. even with proper https://github.com/BenPru/luxtronik/pull/121/commits/17731cfc5fa50d04c177f49b3c3d689e40537b41 implemented.

MSW4-16 + V3.89.1

**Comment by rcreate** [comment]
Me too.

**Comment by BenPru** [comment]
Have you something in the log?

**Comment by AJediIAm** [comment]
![image](https://github.com/BenPru/luxtronik/assets/5879533/6973334e-759b-4669-94df-479158374110)
[config_entry-luxtronik2-d4f28c32d3b8e91d8b225dff9c803ca5.json.txt](https://github.com/BenPru/luxtronik/files/12642908/config_entry-luxtronik2-d4f28c32d3b8e91d8b225dff9c803ca5.json.txt)
The graph clearly shows when I upgraded to the preview version.

**Comment by rcreate** [comment]
Now (preview 20) it works again, perfectly. Thanks so much! 👏

**Comment by BenPru** [comment]
Thansk for the feedback. I close this ticket.
