### ISSUE TITLE
2023.9.12-Alpha-Core-Preview: wrong state-class for "energy" device-class

### ISSUE THREAD

**Issue by AJediIAm** [BenPru/luxtronik#130]
I got the following warning:
![image](https://github.com/BenPru/luxtronik/assets/5879533/5808c2c4-3c4e-4d9e-9df0-3ec1151b1dc9)

Looking into https://developers.home-assistant.io/docs/core/entity/sensor/, I have some doubts about the energy device class. 
Although it is energy output, it is heat energy and not electrical energy which often confuses people. 
Changing the state class from "measurement" to "total increasing" is the easiest fix. 

![image](https://github.com/BenPru/luxtronik/assets/5879533/adb36158-5691-42e4-a21c-f0582bfccaf9)

**Comment by AJediIAm** [comment]
I think you are correct. I found a reference to parameter 257 here which agrees with power as the class: https://community.openhab.org/t/luxtronikheatpump-finding-the-currently-drawn-power/121605/10

**Comment by BenPru** [comment]
Is this fixed?

**Comment by rhammen** [comment]
> Is this fixed?

I did not see these errors anymore, so looks fixed to me.
