### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by euquini** [BenPru/luxtronik#132]
There's no language selection possible in the configuration and therefore (most probably) no devices/entities are available.
How can this be resolved?

**Comment by AJediIAm** [comment]
I'm new to HA development and looking to see if I can pick up some minor fixes, so bare with me :)

I was not expecting a language selection during the setup. Can you explain when and why you expect a language selection?

**Comment by BenPru** [comment]
The language selection is no more needed. In the new code base I read out the ha backend language which is configured in the ha config.
And since ha ~2023.8.* entities and attributes have his own translation possibility. So I can remove my own translation service. But atm this is a todo.

**Comment by BenPru** [comment]
I have tried to implement the new translation service. But unfortunately the entity names are automaticly prefixed by the device name:
![image](https://github.com/BenPru/luxtronik/assets/32298537/23153b10-41b5-400a-8e7d-436dd31a0633)

**Comment by BenPru** [comment]
Should fixed with [2023.10.9-Alpha-Core-Preview](https://github.com/BenPru/luxtronik/releases/tag/2023.10.9-Alpha-Core-Preview)
