### ISSUE TITLE
Pump frequency missing after update to Alpha.Preview 2023.09.19

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#136]
sensor.luxtronik2_pump_frequency is not updated anymore after update to Alpha.Preview 2023.09.19
I do see this in the logs:
2023-09-20 00:10:57.837 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.luxtronik2 entity: sensor.luxtronik2_pump_frequency_2

But I cannot find/see this sensor in the History to create a graph.
And I also do not see this sensor listed as part of the Integration.

**Comment by rhammen** [comment]
I am also missing the following sensors in the Heating device:
- room temperature
- room temperature target

**Comment by BenPru** [comment]
Duplicate #137
