### ISSUE TITLE
In pre-release version 2023.9.19-Alpha-Core-Preview I miss some sensors

### ISSUE THREAD

**Issue by ondras76** [BenPru/luxtronik#139]
Hi, in this version I miss some active entities. Is any chance activate this sensors?
![luxtronik](https://github.com/BenPru/luxtronik/assets/115325615/758e6a03-6486-4976-b644-6366684452e5)

**Comment by BenPru** [comment]
Please provide the full key. It is not visible in the screenshot.
Please note that a few entities have new keys. And some are hidden or disabled by default.

**Comment by Freakandel74** [comment]
Hi, I have issues with only one missing sensor: the Room Temperature (inside the house). I have a termostat device of Alpha Innotec itself which is connected to the heatpump installation. The device sensor is missing in this version.

**Comment by BenPru** [comment]
> Room Temperature

Oh yes. You are right. My plan was to implement it in the climate thermosat. But currently it is not implemented.
Do you only need the read only value?

**Comment by Freakandel74** [comment]
Dit emailadres is buiten gebruik.

**Comment by Freakandel74** [comment]
> > Room Temperature
> 
> Oh yes. You are right. My plan was to implement it in the climate thermosat. But currently it is not implemented. Do you only need the read only value?

Yes, for me read only is fine at the moment.
