### ISSUE TITLE
[META] Can we buy you a couple coffes BenPru? ❤️ 

### ISSUE THREAD

**Issue by FnTm** [BenPru/luxtronik#143]
I just updated from the previous version of Luxtronik2 to the new, Alpha version, and it just worked. Just worked!!

And that got me thinking of how much I appreciate the work that you've been putting in. So I just wanted to drop by and say THANK YOU for all the work that you've put into this integration! ❤️ 🙏 

And also, separately - is there some way to thank you with a coffee or something?

**Comment by BenPru** [comment]
Thank you very much for your recognition, it helps a lot with the current unexplained bugs.
Unfortunately, I no longer have a coffee flat rate at my new employer, but I still drink too much of it. ;-)

**Comment by AJediIAm** [comment]
Can you still give us a paypal account for some small donations?
You can also propose a charity or other developer/project you to support.

**Comment by BenPru** [comment]
I'm creating a github sponsors account. The approval is in progress but pending.
Please support also the initiator if this project: [Bouni](https://github.com/Bouni)

**Comment by BenPru** [comment]
@AJediIAm @FnTm 
You can now sponsor me: https://github.com/sponsors/BenPru
