### ISSUE TITLE
Climate domestic_water thermostat is not migrated to water_heater thermostat

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#146]
Hot water thermostat, which was present in the 'old' integration, is missing in the new integration.
Should I add it back in, or did you remove it on purpose?

**Comment by BenPru** [comment]
It is a new type water heater.
Perhaps the sensor up can migrate it.

**Comment by rhammen** [comment]
Looks like renaming is not trivial... I am not allowed to rename (convert) the climate entity to a water_heater entity...
========================
This error originated from a custom integration.

Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/__init__.py:115
Integration: Luxtronik
First occurred: 12:30:30 AM (1 occurrences)
Last logged: 12:30:30 AM

Could not rename entity climate.luxtronik2_domestic_water->water_heater.luxtronik2_domestic_water
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/__init__.py", line 115, in _up
    ent_reg.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 944, in async_update_entity
    return self._async_update_entity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 879, in _async_update_entity
    raise ValueError("New entity ID should be same domain")
ValueError: New entity ID should be same domain

**Comment by rhammen** [comment]
Changed the title, because the DHW thermostat is indeed present.
Only problem is that the old climate.domestic_water thermostat is not automatically migrated (deleted?)

**Comment by rhammen** [comment]
Since it seems impossible to convert climate.luxtronik2_domestic_water -> water_heater.luxtronik2_domestic_water, maybe the best approach is to delete the existing climate.luxtronik2_domestic_water as part of the migration routine?
That is the best I can come up with.
Or does somebody have another idea?

**Comment by BenPru** [comment]
> Or does somebody have another idea?

No. I think we can not change this.

**Comment by rhammen** [comment]
When we cannot (easily) delete the old  "climate.luxtronik2_domestic_water" climate entity, we must instruct the user to do this.
An alternative would be to (keep) using a "climate.luxtronik_dhw" climate entity instead of the "Water Heater" entity. 
The climate entity looks to be more advanced than the Water Heater entity. E.g. it can show a combined Status/Preset stautus:

Heating (Heat) 26 °C
Currently: 21 °C

As far as I can see, the "Water Hear" entity currently doesn't (can't ?) show the Status, e.g. "Heating" or "Idle"

If we want to keep the Water Heater entity for now then I'm OK with closing this issue: there is no use in keeping open issues that we are not going to solve on relatively short term.

**Comment by BenPru** [comment]
Feel free to reopen if it is not fixed.
