### ISSUE TITLE
Cooling thermostat needs different HVAC_MODE_MAPPING

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#147]
Cooling thermostat needs something like this:
HVAC_COOL_MODE_MAPPING: dict[str, str] = {
    LuxMode.off.value: HVACMode.OFF.value,
    LuxMode.automatic.value: HVACMode.COOL.value,
}

Main issue is that for the Cooling Thermostat, the  LuxMode.automatic.value needs to be mapped to HVACMode.COOL.value instead of HVACMode.HEAT.value.
Currently, when you set Mod e=Cool, you get an error because HVACMode.COOL.value is not defined as a value in HVAC_MODE_MAPPING.

**Comment by BenPru** [comment]
Thanks for your input. Should be fixed with [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta).

**Comment by rhammen** [comment]
Thanks, confirmed it works OK with 2023.10.12 Beta
