### ISSUE TITLE
Missing binary_sensor for compressor1 & compressor2

### ISSUE THREAD

**Issue by Linos88** [BenPru/luxtronik#148]
Ні,
as in #129…

I am only shown the pulses and operating hours of my two compressors.

A compressor is detected but is displayed as Temperaturen

I am missing the binary sensor for the compressors if and which of the two is running.
id: ID_WEB_VD1out 
id: ID_WEB_VD2out

**Comment by BenPru** [comment]
For ID_WEB_VD1out see binary_sensor.luxtronik_*_compressor.
For ID_WEB_VD2out: I will add this in the next prerelease.

**Comment by BenPru** [comment]
See [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta)

**Comment by Linos88** [comment]
Thanks for the great work. It Workshop great.

I still have one wish. It is about writing…
- ID_Einst_Effizienzpumpe_Nominal_akt
- ID_Einst_Effizienzpumpe_Minimal_akt
- ID_Visi_SysEin_EffizienzpumpeNom
- ID_Visi_SysEin_EffizienzpumpeMin

Should I create a new Issue?

**Comment by BenPru** [comment]
> Should I create a new Issue?

Yes. Please provide the following sensor informations for the parameters:
* English Key
* English Name
* Unit
* Min+Max Value
* Step
* Perhaps a factor (How to interpret the value "1000"?)
* device_class
* icon

parameters
867  ID_Einst_Effizienzpumpe_Nominal_akt: 1000
868  ID_Einst_Effizienzpumpe_Minimal_akt: 1000
visiblities
239  ID_Visi_SysEin_EffizienzpumpeNom: 1
240  ID_Visi_SysEin_EffizienzpumpeMin: 1
