### ISSUE TITLE
2023.10.13-Beta: Config flow - already configured 

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#151]
Think this is not really an error, set it to debug?

Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/config_flow.py:269
Integration: Luxtronik
First occurred: 08:49:31 (1 occurrences)

Last logged: 08:49:31

Could not handle config_flow.async_step_dhcp DhcpServiceInfo(ip=‚', hostname='', macaddress='')
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/config_flow.py", line 269, in async_step_dhcp
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1589, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by BenPru** [comment]
> Think this is not really an error, set it to debug?
> 
> self._abort_if_unique_id_configured() File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1589,
> in _abort_if_unique_id_configured raise data_entry_flow.AbortFlow(error)
> homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

This occurs in ha core not in this integration.

But my question is, why the values are empty:
ip, hostname and macaddress
ip=‚', hostname='', macaddress='')

Have you an idea or can you tell me in which case this occurs?

**Comment by Crashman1983** [comment]
host name was empty but IP and MAC were deleted by me.
