### ISSUE TITLE
efficiency pump (HUP) control voltage 

### ISSUE THREAD

**Issue by Linos88** [BenPru/luxtronik#152]
Hello, is it possible to integrate the efficiency pump (HUP) control voltage.

In Luxtronik, the efficiency pump is a control function for the main circulation pump (HUP).
If the efficiency pump is active (switch.luxtronik_xxxx_efficiency_pump)
then the speed of the main circulation pump (HUP) can be set.
The mainboard then outputs a control voltage 3-10V for the main circulation pump (HUP) that then determines the speed.

I have found the following parameters for this.
- Minimal is the speed when the WP is off 
- Nominal is the speed when the WP is active

parameters
867 ID_Einst_Effizienzpumpe_Nominal_akt
868 ID_Einst_Effizienzpumpe_Minimal_akt

visiblities
239 ID_Visi_SysEin_EffizienzpumpeNom
240 ID_Visi_SysEin_EffizienzpumpeMin

- English Key: ?
- English Name (min): „efficiency_pump_minimal“
- English Name (nom): „efficiency_pump_nominal“
- Unit: „V“
- MinValue: 3,0
- MaxValue: 10,0
- Step: 0,5
- Perhaps a factor: not known
- device_class (parameters): „number“
- device_class (visiblities): „sensor“
- icon: „mdi:pump“

Thanks a lot :-)

**Comment by BenPru** [comment]
Thanks.
Can you explain something?
Which pump is set to "efficiency"? circulation_pump_heating, additional_circulation_pump, dhw_recirculation_pump, dhw_circulation_pump or pump_flow?
What or how does this values control?
3-10 Volt means the ElectricPotential provided from heatpump to the pump?
Nominal is the default provided ElectricPotentia and minimal is provided in mode efficiency?
In which cases activates the heatpump this efficiency?

**Comment by BenPru** [comment]
Is available in the main branch. Release comes later.

**Comment by BenPru** [comment]
See [2023.10.14-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.14-Beta)

**Comment by Linos88** [comment]
Wow. Thank you for the work
