### ISSUE TITLE
Solar sensors "active in HA or not" behavior

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#153]
I do not have a solar collector/buffer connected with my heatpump.
In the old integration - after multiple attempts to get it right- , we had the integration code setup such that the solar sensors were not added to the integration in that case --> I liked that :-)

Now, with the new integration, the solar sensors were again present in the integration :-(
I find 2 reasons for that:
1) The new integration did not use the same (lastest) version of _detect_solar_present() as in the old integration, but an earlier version that does incorrectly detect that solar hardware is present when it isn't.
--> not a big deal, I can fix that and will create a PR to do that
I expected that after fixing this, the solar sensors would be automatically removed.
However this was not the case :-(
I suspect this related to the 2nd reason:

2) The new integration seems to have a different approach to adding sensors than the old one:
Luxtronik now adds all specified entities, unless:
- current FW version is lower than required by the entity
- the device does not exist 
- a invisible_if_value value is specified for the entity, which is not (yet?) the case for the solar sensors.
This means the solar sensors are currently always added, even if a user does not have that hardware.

Is this change on purpose?
I'd rather go back to the old behavior...
Would it be OK if I change the behavior back to the old behavior, e.g. by adding an invisible_if_value property to the solar sensors?

**Comment by BenPru** [comment]
Yes, good idea.

**Comment by rhammen** [comment]
Implemented by #154
