### ISSUE TITLE
Missing Entity: Current Heat Output

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#157]
Hi!

In older releases there was an entity that showed me the current heat output while running the heat pump. I could use that for showing current COP (heat output / power consumption). 

This isn't available anymore in newer versions (.10). Can you bring it back?

**Comment by Crashman1983** [comment]
<img width="380" alt="image" src="https://github.com/BenPru/luxtronik/assets/4194672/4bb5f360-a792-43d8-9a92-8af3aee5adad">

it is available in the web interface

**Comment by Kars-de-Jong** [comment]
FYI, the Luxtronik Key for this sensor is `calculations.Heat_Output`.

**Comment by Crashman1983** [comment]
Sorry, found it. Indeed it was hidden and I didn’t see it
