### ISSUE TITLE
Longterm statistics

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#158]
Hi!

Could yo set the stateclass for dhw_heat_amount and heating_amount_heating to total or total increasing? 

His would allow for long term statistics on the sensors. You could do that for others as well!

**Comment by BenPru** [comment]
Has it already:
* [dhw_heat_amount](https://github.com/BenPru/luxtronik/blob/28c22a53cf5f99b5e602509964eaaf3a384bd1f1/custom_components/luxtronik/sensor_entities_predefined.py#L590)
* [heat_amount_heating](https://github.com/BenPru/luxtronik/blob/28c22a53cf5f99b5e602509964eaaf3a384bd1f1/custom_components/luxtronik/sensor_entities_predefined.py#L512)

**Comment by Crashman1983** [comment]
Ok, thank you for response.
