### ISSUE TITLE
Additional sensor YAML

### ISSUE THREAD

**Issue by KHWW** [BenPru/luxtronik#159]
Hello, 

I'm not sure, it could also be my configuration. But when I update to the latest beta version, my extra sensors from the YAML file no longer work.

**Comment by BenPru** [comment]
Yes, read the [docs](https://github.com/BenPru/luxtronik#32-additional-sensors-advanced)/[changelog](https://github.com/BenPru/luxtronik/releases/tag/2023.9.11-Alpha-Core-Preview): No more supported. You can use bounis luxtronik for yaml config values.

I'm trying to get this integration in the HA core project. The guys from HA would like to use no yaml configs.
The plan is to have all sensors out of the box. E.g disabled or default hidden, but the user can activate them.
Which sensor do you miss?

**Comment by KHWW** [comment]
I misread the "read me", sorry! I had my own overview of sensors and automation controls, which no longer worked after the update, so that's correct
