### ISSUE TITLE
Support for multiple Heatpumps

### ISSUE THREAD

**Issue by onemorename** [BenPru/luxtronik#16]
As i try to open a second and/or third heatpump the existing sensor values are overwritten by the new one's.

It would be great if multiple Heatpumps could get added - as this would allow to montor & track the performance and efficiency of them in parallel

**Comment by BenPru** [comment]
I have create a new branch [multiple_heatpumps](https://github.com/BenPru/luxtronik/tree/multiple_heatpumps) for this.
I try to implement the changes for multiple heatpumps in it. Currently it's still work in progress.

**Comment by BenPru** [comment]
Current draf: https://github.com/BenPru/core-1/tree/luxtronik/homeassistant/components/luxtronik
