### ISSUE TITLE
Error message in attributes

### ISSUE THREAD

**Issue by Linos88** [BenPru/luxtronik#168]
Hi,
Can the error message be included in the attributes of "sensor.luxtronik_xxx_error_reason"?

I can read the error message in the card.
<img width="582" alt="Bildschirmfoto 2023-10-22 um 16 00 50" src="https://github.com/BenPru/luxtronik/assets/83694034/3ed06084-bf6b-45bb-9c82-184af5089670">

But in the states I can only see the error code.
<img width="1077" alt="Bildschirmfoto 2023-10-22 um 15 57 22" src="https://github.com/BenPru/luxtronik/assets/83694034/869a719b-f31f-41ae-b817-ffd208076172">

**Comment by BenPru** [comment]
Do you mean you would like to see the Error code and not the Error text in the state?
Thanks for your issue. I realized that the translation for cause and remedy texts are missing in the new version.

**Comment by BenPru** [comment]
Do you mean you would like to see the Error code and not the Error text in the state?
Thanks for your issue. I realized that the translation for cause and remedy texts are missing in the new version.

**Comment by Linos88** [comment]
The Error text in the state (Lovelace UI) is nice👍

Can you enter the error text in the attributes?
![IMG_6372](https://github.com/BenPru/luxtronik/assets/83694034/bc6e62ef-c13d-406a-8d65-c4712724551d)

Thank you very much for the great work. It has become a very good integration

**Comment by BenPru** [comment]
The text is a translation and you can not get it out of the HA functionality.
This wish was rejected from the HA core team: [PR 65743](https://github.com/home-assistant/core/pull/65743)
You can use a plugin for this: [Home-Assistant-custom-components-Custom-Templates](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates)

**Comment by Linos88** [comment]
Ohh wow, that's interesting. Nevertheless, thank you for your support.

I have to think of something else how I can send myself the error text as a notification.

**Comment by Gifford47** [comment]
@Linos88 @BenPru Did managed this issue or is any translation or attribute of the error text available? I´ve still the same issue

**Comment by Linos88** [comment]
@Gifford47 I have not found a way to get the error text. A new sensor must be created for this, with the right data point in the Luxtronic

**Comment by BenPru** [comment]
> @Linos88 @BenPru Did managed this issue or is any translation or attribute of the error text available? I´ve still the same issue

Yes:
![image](https://github.com/BenPru/luxtronik/assets/32298537/88afcfac-6daa-4b46-ba51-9c564d41799d)

**Comment by Gifford47** [comment]
but in the status attributes (code, cause, remedy) there's are only the code 717 stored. like posted [here](https://github.com/BenPru/luxtronik/issues/168#issuecomment-1774142484).
@BenPru can you save the translation of the failure code into the appropriate attributes?

**Comment by Linos88** [comment]
@BenPru 👍. ![ IMG_6491](https://github.com/BenPru/luxtronik/assets/83694034/387a35ef-ca51-4b7d-a3e6-fe80d479fd40) @Gifford47 Search for the "WP last error" sensor, here you will find the error text in the attributes

**Comment by Gifford47** [comment]
Thanks for the answer, but I have the same issue as @Linos88. As you can see, the status attributes have only the code and not the translated text.
In my case I want to send a notification to the mobile phone what the exact error is.
![Screenshot_20231214_200827_Home Assistant.jpg](https://github.com/BenPru/luxtronik/assets/49484063/9dd80321-59d2-41ff-98e7-a5a30cba7893)

**Comment by BenPru** [comment]
> As you can see, the status attributes have only the code and not the translated text.

Yes, the raw value is always the code. The text comes with the translation in the frontend.
And the notfiy services uses the raw values and doesn't make translations - it runs in the backend.

**Comment by Gifford47** [comment]
Ok, but would it be possible to read the appropriate translation JSON file, translate the error reason to a string and save it in the attribute? This could be done every time the sensor has changed. The necessary language is already defined by this awesome integration isn't it? :)
