### ISSUE TITLE
New Luxttronik Firmware V3.89.2-10024 did not connect

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#170]
do i have to change something
I get no connection after new install of firmware

**Comment by BenPru** [comment]
> do i have to change something
> I get no connection after new install of firmware
> 

After a firmware upgrade: Please check the network config from your heatpump and try to connect via mobile app. e.g. Luxprobe.

After the firmware upgrade the Luxtronik often lost the DHCP and IP Config.
Or it is reachable in the network, but the socket doesn't answer.
Can you restart your heat pump? E.g. login as service in the web interface and click restart or power off the heat pump when it's idled.

**Comment by ChrisMisker** [comment]
No problem here with the latest update. (I liked how it showed the update in HA, by the way!)

**Comment by colognebroker** [comment]
Yes after an complete reboot of HA everything ist ok !

**Comment by BenPru** [comment]
Okay, you reboot HA not the heatpump.
Sounds like the reconnect doesn't work anymore. I ty to check it.
BTW: You can restart the integration in the devices view. So you don't need to restart HA. I fixed the integration unload last month.

**Comment by BenPru** [comment]
Okay, you reboot HA not the heatpump.
Sounds like the reconnect doesn't work anymore. I ty to check it.
BTW: You can restart the integration in the devices view. So you don't need to restart HA. I fixed the integration unload last month.

**Comment by BenPru** [comment]
> @ChrisMisker  I liked how it showed the update in HA, by the way!

I have extend the information in the dialog:
![image](https://github.com/BenPru/luxtronik/assets/32298537/c892ceb3-3ea8-4e9b-bc0c-b6f3efc20a32)
