### ISSUE TITLE
Status cooling miss detection when circulation pump runs for heating demand detection

### ISSUE THREAD

**Issue by Kars-de-Jong** [BenPru/luxtronik#172]
I'm running version 2023.9.10, which added detection of (passive) cooling.

I turned on my heating this morning, and noticed that when the heatpump runs the circulation pump to see whether the flow out temperature is below the flow out temperature target, this is miss detected as cooling mode in some cases.

Circulation pump (HUP) is running, heat source pump (VBO) is not running, the temperature of flow in is 0,1 degrees below the temperature of flow out:

![image](https://github.com/BenPru/luxtronik/assets/21991009/28bcf318-eb8c-421b-ae7e-c85fe53d42fa)

After the last heating run the heat source in temperature is below the heat source out temperature (heat source pump is not running):

![image](https://github.com/BenPru/luxtronik/assets/21991009/7f3ddba0-da6b-4bbc-b8a4-b0b127ec8da1)

And now status is set to `cooling`. I believe It should be `no request`.

The detection uses `calculations.ID_WEB_Durchfluss_WQ`, perhaps @rhammen assumed this was the flow of the heat source pump, but it is not, it is the flow of the main circulation pump. Of course when the system is cooling, this pump also runs.

Is it an idea to either check wether the temperature difference is bigger than 0,2 degrees, and/or check wether the VBO pump runs (`calculations.ID_WEB_VBOout` is `true`)?

**Comment by rhammen** [comment]
I'll have a look...

**Comment by Kars-de-Jong** [comment]
FYI, I patched this locally by adding a check on `calculations.ID_WEB_VBOout` being true. That seems to work.

**Comment by BenPru** [comment]
@Kars-de-Jong Is it fixed with the lastest version?

**Comment by rhammen** [comment]
@Kars-de-Jong @BenPru I think this can be closed?

**Comment by BenPru** [comment]
Feel free to reopen if it is not fixed.

**Comment by Kars-de-Jong** [comment]
Sorry, I'm still running the old stable version because the new version doesn't support adding sensors manually.

**Comment by AJediIAm** [comment]
> Sorry, I'm still running the old stable version because the new version doesn't support adding sensors manually.

Which sensors did you add manually?
Maybe we can add them to the latest stable version...
