### ISSUE TITLE
Fehler beim Einrichten , failed setup overnight

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#174]
When i setup heatpump everythig is ok , devices are online.
In the next morning the luxtronik integration could not initialize the heatpump
When i delete integration an set up new , it wprked again.

Any Idea what it is ?

<img width="389" alt="image" src="https://github.com/BenPru/luxtronik/assets/23420078/7b6c42c5-631f-4c3c-9593-eb3ab98f62eb">

**Comment by colognebroker** [comment]
My version
<img width="153" alt="image" src="https://github.com/BenPru/luxtronik/assets/23420078/e9daf6e4-c220-49fc-8ab6-20c703fb100b">

<img width="372" alt="image" src="https://github.com/BenPru/luxtronik/assets/23420078/aa440748-3438-4b05-8b99-0728b15319f4">

**Comment by BenPru** [comment]
Please provide a log and a diag file.

**Comment by BenPru** [comment]
Please try [2023.10.30-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.30-Beta)

**Comment by rhammen** [comment]
@colognebroker Did you try [2023.11.1-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.1-Beta) ?
Is the problem in this issue now resolved for you with that version, or do you still have a problem?

**Comment by colognebroker** [comment]
Yes

**Comment by BenPru** [comment]
Okay, I close this issue now.
