### ISSUE TITLE
ID_WEB_SEC_Qh_Ist hinzufügen funktioniert nicht

### ISSUE THREAD

**Issue by Manuel4342** [BenPru/luxtronik#175]
Hallo,

ich versuche nachträglich den Sensor ID_WEB_SEC_Qh_Ist hinzufügen.
kann mir jemand ein Tipp geben was ich falsch mache?

sensor:
  - platform: luxtronik2
    sensors:
      - group: calculations
        id: ID_WEB_SEC_Qh_Ist
        friendly_name: Ist Wert

**Comment by BenPru** [comment]
Per Yaml konfigurierte Sensoren werden in den neueren Versionen nicht mehr unterstützt.
Dazu musst Du die Integration von Bouni verwenden.
Was sagt der Sensor
ID_WEB_SEC_Qh_Ist
aus?
VL. kann ich den in den Standard aufnehmen.

**Comment by Manuel4342** [comment]
![image](https://github.com/BenPru/luxtronik/assets/149316183/14e1e564-5025-46cc-b6e2-87a60f7289eb)
meine Hoffnung ist das es der wert bei Anlagenstatus "Leistung IST" ist. Desweiteren würde ich mir gerne den Durchfluss (ID_WEB_WMZ_Durchfluss) anzeigen lassen.

was dahinter steckt, wollte ich mir auch anzeigen lassen.
ID_WEB_WMZ_Brauchwasser
ID_WEB_WMZ_Heizung

siehst du eine Möglichkeit die Thermische Desinfektion Manuel zu Starten? ich würde auch gerne die Leistung beeinflussen das ich die Wärmepumpe auf mein PV Leistung anpassen kann.

Danke

Manuel

**Comment by Manuel4342** [comment]
![image](https://github.com/BenPru/luxtronik/assets/149316183/21cf9745-cd98-4e23-991c-42182ad98922)
![image](https://github.com/BenPru/luxtronik/assets/149316183/615c2bbe-df46-4627-98c0-964ee3e15d2d)
es wäre auch schön, wenn die Einstellung weise gleich wäre.
evtl. auch eine eigene Entität in der ich auswählen kann Automatik,Party,Ferien,Aus das wäre dann auch einfach automatisch anzusteuern.

**Comment by BenPru** [comment]
> (ID_WEB_WMZ_Durchfluss) 

ID_WEB_WMZ_Durchfluss > sensor.luxtronik*_heat_amount_flow_rate
![image](https://github.com/BenPru/luxtronik/assets/32298537/55929090-39a2-4606-8bb3-a24b0389cbc4)

> ID_WEB_WMZ_Brauchwasser

sensor.luxtronik*_dhw_heat_amount

> ID_WEB_WMZ_Heizung

sensor.luxtronik*_heat_amount_heating

> siehst du eine Möglichkeit die Thermische Desinfektion Manuel zu Starten?

Da gibt es viele Diskussionen im Forum drüber. Im Endeffekt ist es einfach nur ein Starten der Brauchwasserfunktion mit Zieltemperatur (number.luxtronik*_dhw_thermal_desinfection_target).
Im Attribut last_thermal_desinfection bei number.luxtronik*_dhw_thermal_desinfection_target kannst Du übrigens sehen, wann die Zieltemperatur zuletzt erreicht wurde.

> ich würde auch gerne die Leistung beeinflussen das ich die Wärmepumpe auf mein PV Leistung anpassen kann.

Den Momentan-Verbrauch kannst Du nicht wirklich beeinflussen.
Nur grob steuern war an ist.
Bei mir (LAD7) z.B. verbraucht die Heizung ~2kW, Brauchwasser ~3kW Momentanleistung.

**Comment by BenPru** [comment]
> es wäre auch schön, wenn die Einstellung weise gleich wäre. evtl. auch eine eigene Entität in der ich auswählen kann Automatik,Party,Ferien,Aus das wäre dann auch einfach automatisch anzusteuern.

climate and water_heater sind komplett andere Elemente in HA.
Ich habe die Luxtronik-Begriffe HA Begriffen zugeordnet. In HA sind allgemein gültige Begriffe der Standard und ich finde es nicht zielführend diese Luxtronik-Party-Begriffe zu verwenden.
Ich vergesse immer wieder welche Funktion "Party" und "Ferien" haben.

**Comment by BenPru** [comment]
ID_WEB_SEC_Qh_Ist hört sich für mich "SEC" eher nach Second Heat Generator o.ä. an.
In der Luxtronik Integration gibt es die Möglichkeit eine Diagnose-Datei herunterzuladen.
Da ist ein Dump aller Werte drin.
Lade Dir diese Datei herunter und prüfe "ID_WEB_SEC_Qh_Ist" in verschiedenen Betriebszuständen.
Wenn Du dann weißt was es ist und es benötigst, schreibe das hier gerne rein, dann nehme ich den Sensor auf.

**Comment by Kars-de-Jong** [comment]
The names used for the parameters are mostly German based, so it would surprise me if SEC means Second Heat Generator, since that is called ZWE (Zweiten Wärmeerzeuger) in the manuals, other parameters and screens.

**Comment by BenPru** [comment]
@Manuel4342 Any news?
Do you still need `ID_WEB_SEC_Qh_Ist`?
