### ISSUE TITLE
After a while every sensor of luxtronik is not available ?

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#176]
Is this what happend to others too?

After reboot of HA everything is ok !

**Comment by BenPru** [comment]
Which versions do you use? HA+Integration
Please provide a log and a diag file.

**Comment by rhammen** [comment]
I observed the same problem with 2023.10.20-Alpha. After several hours the luxtronik sensors disappear.
The error-message in the logs that signals the problem has occurred is:
2023-10-29 10:07:13.503 ERROR (MainThread) [custom_components.luxtronik2] Error fetching luxtronik2 data: Read: Error communicating with device

I have just now installed 2023.10.28-Beta (but I expect no change from that).

On further thinking, I remembered I setup a script on my NAS years ago that also fetches data from the Heatpump.
I want to rule out that there is any influence from this, so I have now disabled this script.

Where can I configure the Data Package Length?
I looked under the Integration-->Configure, but there I can only configure the Room temperature sensor.
I may play around to see if I can find any effect.

In the diagnostic file I found my current value is:
"max_data_length": 10000,
Can you measure/log the current package length, so we can see if it is close to the current max_data_length?

**Comment by colognebroker** [comment]
exact my problem !
BenPru
What is your max Data Package Length config? You could try to set it =50000.
Where can i config this ?

**Comment by BenPru** [comment]
> Where can I configure the Data Package Length?

In the first setup dialog or manually in .storage/core.config_entries

**Comment by BenPru** [comment]
I think the reconnect doesn't work reliable. I have the same after a firmware update or restart of the heatpump.
If your network is not very stable you can have it in the normal operation.
I have changed samething in the socket connection. I push it in the main branch without release.

**Comment by colognebroker** [comment]
i can not find max Data Package Length in .storage/core.config_entries
;-(

**Comment by BenPru** [comment]
Please try [2023.10.30-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.30-Beta)

**Comment by colognebroker** [comment]
I have done this, now no devices are available …
I go back on .28-beta
After I go back devices appear

**Comment by colognebroker** [comment]
<img width="1410" alt="image" src="https://github.com/BenPru/luxtronik/assets/23420078/765eb2b0-908f-4702-b09f-33e11e9eb100">

**Comment by colognebroker** [comment]
also with 31-beta

**Comment by colognebroker** [comment]
Platform error sensor.luxtronik2 - Exception importing custom_components.luxtronik2.sensor

could not find a way back downgrading did not work 

Attention
cannot delete integration successfully

you need a backup to restore

**Comment by rhammen** [comment]
> I think the reconnect doesn't work reliable. I have the same after a firmware update or restart of the heatpump. If your network is not very stable you can have it in the normal operation. I have changed samething in the socket connection. I push it in the main branch without release.

I'm running 2023.10.30 Beta
There is bad news 😢 , but also good news 😄 

- (the bad news) This evening I still got the communication error:

This error originated from a custom integration.

Logger: custom_components.luxtronik2
Source: helpers/update_coordinator.py:322
Integration: Luxtronik
First occurred: 20:08:01 (1 occurrences)
Last logged: 20:08:01

Error fetching luxtronik2 data: Read: Error communicating with device

- (the good news) The sensor was only gone for 1 minute, and re-appeared afterwards!
Thanks for this fix/significant impovement!

**Comment by rhammen** [comment]
@colognebroker Did you try [2023.11.1-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.1-Beta) ?
Is the problem in this issue also resolved for you with that version, or do you still have a problem?

**Comment by colognebroker** [comment]
I am not sure , because one time devices are not available, but after last restart it work for hours now
We will see tomorrow

**Comment by BenPru** [comment]
> We will see tomorrow

@colognebroker Is it fixed for you?

**Comment by BenPru** [comment]
@colognebroker I close this issue. Feel free to re-open if needed.
