### ISSUE TITLE
kW/h counters always at 0

### ISSUE THREAD

**Issue by scaronni** [BenPru/luxtronik#18]
Hello,

I have a Luxtronik 2.0 controller on firmware 1.86.2 attached to an LW-100 H-A heat pump, all the kW/h counters are always at 0.

- Heatpump: `sensor.luxtronik2_heat_amount_counter`
- Domestic water: `sensor.luxtronik2_heat_amount_domestic_water`
- Heating: `sensor.luxtronik2_heat_amount_heating`

The download section of Alpha Innotec only gives me 1.86.2 as the last version available, so not sure if it's a firmware limitation.

Thanks.

**Comment by Kars-de-Jong** [comment]
Do you have values in your heat counters when viewed from the web interface or on the display of the heatpump itself?

**Comment by BenPru** [comment]
@scaronni Alternative: Can you Run the [bouni dump script](https://gist.githubusercontent.com/Bouni/cf0dc2c7c53c32deeb264803ec350e5c/raw/4ae9f92065bfc177e927c847e1583cc70929183a/dump-luxtronik.py)?
Die you geht the values in this results?

**Comment by scaronni** [comment]
Here is the output from port 8888 and 8889. Depending on the two is slightly different.

[8888.txt](https://github.com/BenPru/luxtronik/files/10002257/8888.txt)
[8889.txt](https://github.com/BenPru/luxtronik/files/10002258/8889.txt)

Here is the diff between the two:

[diff.txt](https://github.com/BenPru/luxtronik/files/10002261/diff.txt)

Thanks!

**Comment by scaronni** [comment]
> Do you have values in your heat counters when viewed from the web interface or on the display of the heatpump itself?

I have no information about the kW/h in the web interface, as in no entries at all, not just `0` as the value. But the max firmware I can load in this Luxtronik 2.0 is version 1.86.2, so that's why I asked about the firmware limitation.

Does anybody know a way to update the Luxtronik firmware separately from the heat pump? The wizard on the AIT website always points me to 1.86.2.

**Comment by scaronni** [comment]
> Do you have values in your heat counters when viewed from the web interface or on the display of the heatpump itself?

Do you know in which submenu to look for the information?

**Comment by BenPru** [comment]
> Here is the output from port 8888 and 8889. Depending on the two is slightly different.
> 
> [8888.txt](https://github.com/BenPru/luxtronik/files/10002257/8888.txt) [8889.txt](https://github.com/BenPru/luxtronik/files/10002258/8889.txt)

Heatpump: sensor.luxtronik2_heat_amount_counter
	calculations.ID_WEB_WMZ_Seit
Domestic water: sensor.luxtronik2_heat_amount_domestic_water
	calculations.ID_WEB_WMZ_Brauchwasser
Heating: sensor.luxtronik2_heat_amount_heating
	calculations.ID_WEB_WMZ_Heizung

All values are 0 in your Export.
Submenu heatpower in heatpump24.com.

**Comment by scaronni** [comment]
Thanks. I did not know what to look for. Apparently my system is not reporting it and it's by design, I've gone through the whole heatpump24 and I don't see any heat power submenu or any entry reporting something in kW/h.

Bummer.

Thanks for the help.
