### ISSUE TITLE
"Error migrating" after upgrade to 2023.10.30-Beta

### ISSUE THREAD

**Issue by 02curls** [BenPru/luxtronik#182]
lost all entities after upgrading to 2023.10.30-Beta

Logger: homeassistant.config_entries
Source: config_entries.py:658
First occurred: 10:37:09 (1 occurrences)
Last logged: 10:37:09

Error migrating entry Alpha Innotec SWC 240422-060 for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 658, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/__init__.py", line 141, in async_migrate_entry
    _up("heat_amount_domestic_water", SK.DHW_HEAT_AMOUNT)
  File "/config/custom_components/luxtronik2/__init__.py", line 110, in _up
    if prefix is None or ent_reg is None:
       ^^^^^^
UnboundLocalError: cannot access local variable 'prefix' where it is not associated with a value

**Comment by arnebret** [comment]
Identical here

**Comment by mwatermann** [comment]
Same here

Question: Can I easily go back to last version? Cannot find the menu but I think I saw it somewhen...?

**Comment by mwatermann** [comment]
> Same here
> 
> Question: Can I easily go back to last version? Cannot find the menu but I think I saw it somewhen...?

Got it (just used download button in HACS integration again and choosed the last version .28 => works fine again).

**Comment by idominiki** [comment]
Hi @BenPru 

.31 Beta Integration can't setup 

'Logger: homeassistant.setup
Source: setup.py:215
First occurred: 21:15:04 (1 occurrences)
Last logged: 21:15:04

Setup failed for custom integration luxtronik2: Unable to import component: Exception importing custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 13, in <module>
    from .const import (
  File "/config/custom_components/luxtronik2/const.py", line 62, in <module>
    SERVICE_WRITE_SCHEMA = vol.Schema(
                           ^^^
NameError: name 'vol' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.luxtronik2
'

**Comment by colognebroker** [comment]
i think benpru will fix it quick

**Comment by woozar** [comment]
Thanks @mwatermann - such a "tiny" tipp that prevented all that backup restore bullshit for me :)

**Comment by colognebroker** [comment]
in this case if you uploaded .31-bata it did not work to reload via hacs
it is somehow destroyed

**Comment by colognebroker** [comment]
everything is okj now after last fix

**Comment by rhammen** [comment]
@02curls @evdb-arne @mwatermann @idominiki Did you try [2023.11.1-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.1-Beta) ?
Is the problem in this issue now resolved for you with that version, or do you still have a problem?

**Comment by mwatermann** [comment]
> @02curls @evdb-arne @mwatermann @idominiki Did you try [2023.11.1-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.1-Beta) ? Is the problem in this issue now resolved for you with that version, or do you still have a problem?

After colognebrokers reply

> "in this case if you uploaded .31-bata it did not work to reload via hacs
> it is somehow destroyed" 

I did not dare to install another one after .29, yet  :-/
But I guess I will try it this weekend.

**Comment by 02curls** [comment]
@mwatermann  I am on [2023.11.1-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.1-Beta) now, "Error migrating" fixed, 

but I believe that after HA upgrade today, most my Luxtronic entities are suddenly empty
this is my current HA version:
Core 2023.11.1
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231030.1

**Comment by BenPru** [comment]
> but I believe that after HA upgrade today, most my Luxtronic entities are suddenly empty

Can you provide a log and diag file?
