### ISSUE TITLE
Error occurred loading flow for integration luxtronik2

### ISSUE THREAD

**Issue by woozar** [BenPru/luxtronik#184]
I was running 2023.10.20-Alpha (I am 90% sure, it was 10.20) and it was working fine.
Then i updated to 2023.10.31-Beta and the integration did no longer start after restarting home assistant. 
Then I downgraded to 2023.10.20-Alpha and rebootet home assistant and I get the same error. 

See Home Assistant Core logs:
> Error occurred loading flow for integration luxtronik2: Exception importing custom_components.luxtronik2.config_flow
1:55:14 PM – (ERROR) config_entries.py
Unexpected exception importing platform custom_components.luxtronik2.config_flow
1:55:14 PM – (ERROR) loader.py
Setup failed for custom integration luxtronik2: Unable to import component: Exception importing custom_components.luxtronik2
1:54:55 PM – (ERROR) setup.py
Unexpected exception importing component custom_components.luxtronik2
1:54:55 PM – (ERROR) loader.py

Please help

**Comment by colognebroker** [comment]
yes you need a backup

**Comment by Ronicon98** [comment]
Same problem. Downgrade to 2023.10.20 did not resolve the issue.

**Comment by colognebroker** [comment]
Use the fix wich benpru provided in const.py

Then it works

**Comment by qubabos** [comment]
Where do I find this fix?

**Comment by colognebroker** [comment]
https://github.com/BenPru/luxtronik/commit/fc7bdf5c063678b3425278b66bb62480d56e5666￼
* Fix missing import · ***@***.***
github.com

**Comment by woozar** [comment]
"Access to GitHub was denied" if I click that link

**Comment by woozar** [comment]
2023.11.1-Beta from HACS fixes this issue.
Thank you <3
