### ISSUE TITLE
Energy counters for secondary heat sources

### ISSUE THREAD

**Issue by matuspu** [BenPru/luxtronik#185]
Dear BenPru and developers!
I have an Alpha Innotec heatpump and using 2023.9.10 integration. Due to a hardware sensor problem my HP is running a lot on secondary heat source for both heating and hot water. Energy consumed for secondary heat source is shown separately on the heatpump24.com website, but it does not appear anywhere in HA. HA only shows energy consumed for heatpump. I do not see any entities realted to 2nd heat source in HA. 
Is there a way to show energy consumed by second heating source in HA?

Thank you for a great integration!
Matus

**Comment by matuspu** [comment]
I will try to add it manually if I can find it in original Bouni documentation. It might be nice to add these counters automatically.

**Comment by BenPru** [comment]
> Is there a way to show energy consumed by second heating source in HA?

Do you mean "parameters.ID_Waermemenge_ZWE"? --> See additional_heat_generator_amount_counter.
If you don't see the sensor you can manually activate it in the hidden sensors under the device.
The luxtronik visiblity-flags are often wrong and many users don't need all entities. So some sensors are hidden by default.

**Comment by BenPru** [comment]
@matuspu Have you found the correct sensor?
