### ISSUE TITLE
missing sensor

### ISSUE THREAD

**Issue by Mehli12** [BenPru/luxtronik#195]
hi, I installed  the 2023.11.1 beta.
many thanks for your hard work on this integration!
in my test environment and it worked well. now I installed it in my productive environment and I miss, so fare, 2 sensors:

sensor.luxtronik2_current_heat_output

and 

sensor.luxtronik2_pump_frequency

in my test environment it is available but not on my productive.
any idea?
 I checked the files in custom_components. they look like the same for me. at least these 2 sensors are in the file "sensor_entities_predefined.py" in both enviroements.

**Comment by BenPru** [comment]
They are hidden, you can activate them in the device.

**Comment by Mehli12** [comment]
Thank you. That's it.
