### ISSUE TITLE
most Luxtronic entities lost

### ISSUE THREAD

**Issue by 02curls** [BenPru/luxtronik#196]
probably after upgrading HA core to 2023.11.1 I lost pretty much all Luxtronic entities today afternoon on Luxtronic 2023.11.1-beta, 
downgrading to HA core to 2023.11.1 did not help, so did not downgrading to Luxtronic 2023.10.28-beta
error logs:
Unexpected error fetching luxtronik2 data: Sensor sensor.luxtronik2_switchoff_reason provides state value '0', which is not in the list of options provided
21:29:39 – (CHYBA) Luxtronik (vlastní integrace) - zpráva se poprvé objevila v 21:15:38 a zobrazuje se 19x
Get_sensor ID_Switchoff_file_{ID}_0 returns None
21:29:39 – (VAROVÁNÍ) Luxtronik (vlastní integrace) - zpráva se poprvé objevila v 21:15:36 a zobrazuje se 22x
Parameter 'ID_Switchoff_file_{ID}_0' not found
21:29:39 – (VAROVÁNÍ) Luxtronik (vlastní integrace) - zpráva se poprvé objevila v 21:15:36 a zobrazuje se 22x
Error while setting up luxtronik2 platform for climate
21:15:39 – (CHYBA) Klima
Error while setting up luxtronik2 platform for water_heater
21:15:39 – (CHYBA) Water Heater
Error while setting up luxtronik2 platform for switch
21:15:38 – (CHYBA) Vypínač
Error while setting up luxtronik2 platform for number
21:15:38 – (CHYBA) Číslo
<img width="354" alt="Screenshot 2023-11-05 at 21 51 52" src="https://github.com/BenPru/luxtronik/assets/107803294/c6d0d2aa-426a-49e1-a8c4-76806b0875fc">
<img width="355" alt="Screenshot 2023-11-05 at 21 52 02" src="https://github.com/BenPru/luxtronik/assets/107803294/59458102-5af5-4f4b-84a4-90551fb6ed06">
<img width="360" alt="Screenshot 2023-11-05 at 21 52 15" src="https://github.com/BenPru/luxtronik/assets/107803294/bf790b8d-4135-47fa-9d74-dfcbfca65ad9">
<img width="358" alt="Screenshot 2023-11-05 at 21 52 24" src="https://github.com/BenPru/luxtronik/assets/107803294/e54a13db-9471-453c-8c43-69a510e27b0f">
<img width="363" alt="Screenshot 2023-11-05 at 21 52 34" src="https://github.com/BenPru/luxtronik/assets/107803294/d9525f41-fdcd-48fd-9251-1847141a3a11">

**Comment by colognebroker** [comment]
for me it works with 
![image](https://github.com/BenPru/luxtronik/assets/23420078/3afd0c73-7408-44db-8f71-dff0038d3d90)

and
![image](https://github.com/BenPru/luxtronik/assets/23420078/fd25a807-dfc4-4f85-9d0d-536a4aa33433)

**Comment by colognebroker** [comment]
and 
with 23.11.1 too

**Comment by 02curls** [comment]
not for me

**Comment by 02curls** [comment]
full log [home-assistant_2023-11-06T06-12-52.473Z.log](https://github.com/BenPru/luxtronik/files/13263094/home-assistant_2023-11-06T06-12-52.473Z.log)

**Comment by BenPru** [comment]
@02curls Please try the current main branch.

**Comment by 02curls** [comment]
Today I restored from full backup, then upgraded both HA to latest release and Luxtronik to latest beta release, all is working for now

**Comment by BenPru** [comment]
@02curls Can we close this issue?

**Comment by 02curls** [comment]
so the issue is back, not after any upgrade, no particular reason that I can think of,
just again lost the entities today after 12:58:33
<img width="1183" alt="Screenshot 2023-11-12 at 15 44 59" src="https://github.com/BenPru/luxtronik/assets/107803294/e5ae2f7c-a2c4-47d0-b429-bffd1dc78cef">
[home-assistant_2023-11-12T14-48-04.649Z.log](https://github.com/BenPru/luxtronik/files/13328342/home-assistant_2023-11-12T14-48-04.649Z.log)

**Comment by 02curls** [comment]
@BenPru so it seems that I keep loosing some entities right after sensor.luxtronik2_status_line_3 enters the "cycle lock" status (no idea what that is, but it usually follows the "domestic water" status)

the entities I keep loosing are the following for example:
number.luxtronik2_dhw_target_temperature
number.luxtronik2_heating_target_correction_2
all the number.luxtronik2_heating_circuit_curve......

[home-assistant_2023-11-12T18-30-26.856Z.log](https://github.com/BenPru/luxtronik/files/13328796/home-assistant_2023-11-12T18-30-26.856Z.log)

**Comment by BenPru** [comment]
@02curls "Cylcle Lock" is a lock time between switch off and switch on the heatpump. This happens often then heating ends and hot water starts. I avoid this with automations.
The source of your error is a missing value 0 in the enum. I have added it.
Please try [2023.11.12-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.12-Beta)

**Comment by 02curls** [comment]
@BenPru thank you, [2023.11.12-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.12-Beta) resolves the issue
