### ISSUE TITLE
novelan ld7 

### ISSUE THREAD

**Issue by Frnkmn** [BenPru/luxtronik#197]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/__init__.py:185
Integration: Luxtronik
First occurred: 09:25:55 (1 occurrences)
Last logged: 09:25:55

Bad logger message: Remove service! ((TypeError("object NoneType can't be used in 'await' expression"),))
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/__init__.py", line 185, in async_unload_entry
    await hass.services.async_remove(DOMAIN, SERVICE_WRITE)
TypeError: object NoneType can't be used in 'await' expression

**Comment by BenPru** [comment]
Logger: homeassistant.components.update
Source: helpers/entity_platform.py:621
Integration: Aktualisieren (documentation, issues)
First occurred: 09:25:25 (1 occurrences)
Last logged: 09:25:25

luxtronik2: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.178.58/', 'default_manufacturer': 'Alpha Innotec', 'default_model': '', 'default_name': 'Wärmepumpe', 'identifiers': {('luxtronik2', '231015_0261_heatpump')}, 'manufacturer': 'Novelan', 'model': 'LD7', 'name': 'Wärmepumpe 231015-0261', 'suggested_area': 'Utility room', 'sw_version': 'V2.88.3'} for 'luxtronik2' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by BenPru** [comment]
@Frnkmn I can see that you don't use the latest luxtronik integration.
If you use HA >2023.9.* please install the latest luxtronik integration.

**Comment by Frnkmn** [comment]
@BenPru Danke schön, das war das Problem. Ich habe die neue Beta installiert und es funktioniert.
