### ISSUE TITLE
Climate thermostat domestic water

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#2]
Creating a home assistant climate thermostat for the domestic water.

Current state: **partial working**
Adds hardcoded climate entity

TODO:
- [x] **Fix gui delay** after writing new values.
- [x] Create **unique id**
- [x] Check the underlying luxtronik **sensor names**.
- [x] Allow **control mode luxtronik** and **home assistant**. Mode Home assistant=Thermostat idle means state off in luxtronik. Home assistant is the primary controller! Mode luxtronik means the thermostat writes only the target temperature to luxtronik, preset and hvac modes. The On/Off state is handled by luxtronik and the thermostat shows only the current state.
- [x] Translation
- [x] Allow to **overwrite** the underlying luxtronik **sensor names**.?

**Comment by BenPru** [comment]
@Bouni Do you have an idea how to debounce an async method in python? (Python has not been my professional base more for the past two years 🙈)
Or do you know a ha dev forum to place this question? In the normal forum I get not very much respone for such special questions.
The background is that the thermostat or a number entity (e.g. heating_temperature_correction) is working general. But if I use the input in home assistant the write function is called for every 0.5 C° step and the gui gets race conditions with the read function.

**Comment by Cees-van-Beek** [comment]
Perhaps the AppDaemon addon could be of use for you:
https://appdaemon.readthedocs.io/en/latest/

**Comment by BenPru** [comment]
> Do you have an idea how to debounce an async method in python?

I have fixed it with calling a sync-debounced-method in the async method. This works fine.
