### ISSUE TITLE
Flow Rate Value

### ISSUE THREAD

**Issue by busa-projects** [BenPru/luxtronik#20]
Hi

Thanks for the Component! It's very helpful!  Question: is there a Posibility to integrate the flow Rate reading of the WP? Would be grate to ensure that the flow Rate is not falling below the min Flow Rate of the WP when closing Valves.

BR busa

**Comment by rhammen** [comment]
Do you know which sensor(s) corresponds to the flow?
The full list of sensors is @ https://github.com/Bouni/python-luxtronik/blob/main/luxtronik/calculations.py
There are only a couple of sensors marked as flow.
You can add them yourself to your configuration.yaml:

sensor:
  - platform: luxtronik2
    sensors:
      - group: calculations
        id: ID_WEB_WMZ_Durchfluss 
        friendly_name: Flow_WMZ
        state_class: measurement
      - group: calculations
        id: ID_WEB_Durchfluss_WQ
        friendly_name: Flow_WQ
        state_class: measurement

Try it, and confirm if these are the sensors you need.
In an update these could be added to the integration.

**Comment by busa-projects** [comment]
Integration with the Configuration.yaml works flawlessly. thx!

Both Sensors have the same Value on my System and correspond to the Webfrontent of the Luxtronic. One is the WMZ (Wärmemängenzähler Durchfluss  => Heat Amount Counter Flow) and the other is WQ (Wärmequelle Durchfluss => Heat Source Flow). I'm not sure if the Overflow Valve will impact one of the two. So better do integrate both.
