### ISSUE TITLE
Update Home Assist

### ISSUE THREAD

**Issue by Bello2023** [BenPru/luxtronik#200]
Hello, 
When I perform an update from Home Assistant version 2023.8.4 to 2023.11, Luxtronic stops working. Do I have the correct version of Luxtronic? There is no update available. Do you know what could be the issue and how I can resolve it?

**Comment by BenPru** [comment]
For HA >2023.9 please use the latest beta.
Backup your config and read the breaking changes.
You have to activate "betas" in HACS.

**Comment by Laars123** [comment]
Can you give an indication as to when the main release will be updated to support HA >2023.9 please? Thank you!

**Comment by Bello2023** [comment]
It is in my schedule to carry out this during the upcoming weekend.

 

Met vriendelijke groet,

Hans van Berlo

 ***@***.***> ***@***.***

 

Van: lars ***@***.***> 
Verzonden: donderdag 16 november 2023 23:56
Aan: BenPru/luxtronik ***@***.***>
CC: Bello2023 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BenPru/luxtronik] Update Home Assist (Issue #200)

 

Can you give an indication as to when the main release will be updated to support HA >2023.9 please? Thank you!

**Comment by Bello2023** [comment]
Hello,

 

I have performed the following steps:

• Hacs: Display beta versions 'on.'

• Installed HA 2023.9.

• Reinstalled Luxtronik. Beta version 'on.' I can only choose version 2023.01.01.

• After restarting everything each time, the parameters for Luxtronik are 'Not available.'

The error messages I receive include: 2023-11-17 11:28:20.119 ERROR (MainThread) [homeassistant.components.switch] luxtronik2: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'https://www.heatpump24.com/DownloadArea.php?layout=1', 'default_name': 'Heating', 'identifiers': {('luxtronik2', '290415_017_heating')}, 'manufacturer': 'Alpha Innotec', 'model': 'MSW2-6S', 'name': 'Heating'} for 'luxtronik2' config entry: device info needs to either describe a device, link to an existing device, or provide extra information.

 

What am I doing wrong?"

 

Met vriendelijke groet,

Hans van Berlo

 ***@***.***> ***@***.***

 

Van: BenPru ***@***.***> 
Verzonden: dinsdag 14 november 2023 18:21
Aan: BenPru/luxtronik ***@***.***>
CC: Bello2023 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BenPru/luxtronik] Update Home Assist (Issue #200)

 

For HA >2023.9 please use the latest beta.
Backup your config and read the breaking changes.
You have to activate "betas" in HACS.

**Comment by BenPru** [comment]
> 2023.01.01

This is the latest Version from the repo Bouni\Luxtronik.
Please ensure to use the repo BenPru\Luxtronik

**Comment by Bello2023** [comment]
This is clear. I have now followed the installation guide from BenPru/luxtronik. After adding, I get the message: Repository 'benpru/luxtronik' exists in the store. However, I do not see it here?

 

Met vriendelijke groet,

Hans van Berlo

 ***@***.***> ***@***.***

 

Van: BenPru ***@***.***> 
Verzonden: vrijdag 17 november 2023 13:39
Aan: BenPru/luxtronik ***@***.***>
CC: Bello2023 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BenPru/luxtronik] Update Home Assist (Issue #200)

 

2023.01.01

This is the latest Version from the repo Bouni\Luxtronik.
Please ensure to use the repo BenPru\Luxtronik

**Comment by BenPru** [comment]
> This is clear. I have now followed the installation guide from BenPru/luxtronik.
> After adding, I get the message: Repository 'benpru/luxtronik' exists in the store.

With this you have added the customized repo to your HACS.

> However, I do not see it here?

If you open HACS and type "luxtronik" in the search bar, you should see two luxtronik results.
The one with the blue "Download"-Arrow is the correct one:
![image](https://github.com/BenPru/luxtronik/assets/32298537/1e8ecd5f-5b9d-4ebd-b7bf-72b10e3c81fb)

**Comment by BenPru** [comment]
> Can you give an indication as to when the main release will be updated to support HA >2023.9 please? Thank you!

@Bello2023 I think I was meant by the question.
@Laars123 The Migration of the breaking changes is the problem. I have to make more tests and extend the documentation. Otherwise I'm very afraid of getting a lot of questions and a shitstorm.
I hope I can make it in the next 2-3 weeks.

**Comment by Bello2023** [comment]
It's working again. The update has now been successfully executed. Thanks for your help.

**Comment by Laars123** [comment]
@BenPru, you're right, I meant you with my question :) Thanks for the update, looking forward to it!
