### ISSUE TITLE
service to bypass hot water block  /  Dienst um die Brauchwassersperre zu umgehen

### ISSUE THREAD

**Issue by kroessig** [BenPru/luxtronik#203]
hello, 
does this integration provide a service to bypass the hot water block (time interval)?
I would have thought this was available in the old version. But I only migrated to the new HA 2 weeks ago and can't find this service.

Hallo, 
stellt diese Integration einen Dienst bereit, um die Brauchwassersperre zu umgehen (Zeitintervalll)? 
Ich hätte gedacht in der alten Version gab es diesen. Habe aber erst vor 2 Wochen zu der neuen HA migriert und finde diesen Dienst nicht.

**Comment by BenPru** [comment]
Der einzige Dienst der bereitgestellt wird, ist luxtronik.write. Damit kann jeder beliebige Parameter geschrieben werden.
Was meinst Du mit "Brauchwassersperre"?
Die EVU-Netzsperre? --> Die kannst Du umgehen, indem Du den Zweitwärmeerzeuger frei schaltest. Das sollte aber ohne Dienst gehen.

**Comment by kroessig** [comment]
Ich meine die "Schnellladung". (habe gerade nachgeschaut, wie es heißt)
Ich habe meine WP an "normalen Strom", da ich eine PV Anlage habe. 
manuell geht es so:
![PXL_20231121_214602349](https://github.com/BenPru/luxtronik/assets/139384422/3ab58548-6b36-471d-97c5-579a99e518f9)
![PXL_20231121_214611280 MP](https://github.com/BenPru/luxtronik/assets/139384422/d67cfe9b-68a3-4908-bd9b-e66a7231f496)

**Comment by BenPru** [comment]
Da bin ich überfragt.
Du könntest mit meinen Modul einen Dump aller Parameter via Diag File machen.
Einmal Schnellladung inaktiv und einmal aktiv und beide Dateien hier anhängen.
VL. finde ich einen relevanten Unterschied und den entsprechenden Parameter.
Wie man eine Diag Datei erstellt, steht im Readme.

**Comment by kroessig** [comment]
Hallo, hier die Unterschiede, anbei aber auch nochmal beide Dateien.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kroes/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kroes/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


"11   ID_WEB_Temperatur_TRL                                         ": "24.4", | "11     ID_WEB_Temperatur_TRL                                         ": "23.6",
-- | --
"38   ID_WEB_BUPout                                                 ": "False", | "38   ID_WEB_BUPout                                                 ": "True",
"40   ID_WEB_MA1out                                                 ": "False", | "40   ID_WEB_MA1out                                                 ": "True",
"41   ID_WEB_MZ1out                                                 ": "True", | "41   ID_WEB_MZ1out                                                 ": "False",
"48   ID_WEB_ZW1out                                                 ": "False", | "48   ID_WEB_ZW1out                                                 ": "True",
"60     ID_WEB_Zaehler_BetrZeitZWE1                                 ":   "1669526", | "60   ID_WEB_Zaehler_BetrZeitZWE1                                 ":   "1669538",
"68     ID_WEB_Time_ZWE1_akt                                          ": "0", | "68   ID_WEB_Time_ZWE1_akt                                          ": "12",
"73     ID_WEB_Time_VDStd_akt                                         ": "6232", | "73   ID_WEB_Time_VDStd_akt                                         ": "6262",
"80   ID_WEB_WP_BZ_akt                                              ": "no request", | "80   ID_WEB_WP_BZ_akt                                              ": "hot water",
"117    ID_WEB_HauptMenuStatus_Zeile1                               ":   "heatpump idle", | "117  ID_WEB_HauptMenuStatus_Zeile1                               ":   "heatpump coming",
"118    ID_WEB_HauptMenuStatus_Zeile2                               ":   "since", | "118  ID_WEB_HauptMenuStatus_Zeile2                               ":   "in",
"119    ID_WEB_HauptMenuStatus_Zeile3                               ":   "no request", | "119  ID_WEB_HauptMenuStatus_Zeile3                               ":   "pump forerun",
"120    ID_WEB_HauptMenuStatus_Zeit                                 ":   "6221", | "120  ID_WEB_HauptMenuStatus_Zeit                                 ":   "6251",
"134    ID_WEB_AktuelleTimeStamp                                    ":   "2023-11-22 18:31:13", | "134  ID_WEB_AktuelleTimeStamp                                    ":   "2023-11-22 18:31:43",
"157    ID_WEB_AnalogOut2                                             ": "40.0", | "157  ID_WEB_AnalogOut2                                             ": "100.0",
"175    ID_WEB_LIN_ANSAUG_VERDAMPFER                                ":   "8.2", | "175  ID_WEB_LIN_ANSAUG_VERDAMPFER                                ":   "8.1",
"180  ID_WEB_LIN_HD                                                 ": "3.69", | "180  ID_WEB_LIN_HD                                                 ": "3.62",
"181  ID_WEB_LIN_ND                                                 ": "3.7", | "181  ID_WEB_LIN_ND                                                 ": "3.68",



</body>

</html>

Von den IDs kommen ja nur 38, 40, 41, 48 in Frage. 
Nr. 48:  "Ausgang "Steuersignal Zusatzheizung v. Heizung"" scheint es wohl zu sein. 
https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1533935933/Java+Webinterface

JEDOCH, es scheint wohl, dass ich mit der Schnellladung den Zusatzheizer einschalte.... 
Im HA wird die Entität:  Zusätzlicher Wärmeerzeuge"  (binary_sensor.luxtronik2_additional_heat_generator) aktiviert.

Im [Handbuch](https://www.alpha-innotec.ch/fileadmin/content/downloads/Lux_Endkunde_de.pdf) auf Seite 16 steht leider nix, ob da die richtige WP an geht oder die Heizstäbe... Werde das morgen aber nochmal vor Ort prüfen.

**Comment by BenPru** [comment]
Param 48 ist "zusätzlicher Wärmeerzeuger" / Heizstab (binary_sensor.luxtronik*_additional_heat_generator).
Das bei einer Schnellladung der Heizstab angeht, davon war ich ausgegangen.
Ob der Verdichter auch läuft, kannst Du an binary_sensor.luxtronik*_compressor == true sehen. Laut Deinen Logs war der aus.
Leider ist aus den Daten nicht erkennbar, wie man eine Schnellladung aktiviert. Vielleicht ist dies auch nur intern in der Firmware realisiert.

---

Warum arbeitest Du mit Sperrzeiten der Wärmepumpe?
Die meisten Benutzer verwenden diese nicht und steuern das über HA.
Du kannst ja einfach eine Automatisierung anlegen und Nachts water_heater.luxtronik*_domestic_water Modus = aus setzen.
Brauchst Du dann doch dringend Wasser, kannst Du den Modus wieder ändern und die Zieltemperatur hoch setzen. Dann springt die Wärmepumpe ohne Heizstab an. Sicher kann man den Heizstab auch noch erzwingen.
Alternativ kannst Du den Modus dauerhaft auf Wärmepumpe stehen lassen und das über die Zieltemperatur steuern. Dann würde die WP automatisch anspringen, wenn die Zielt. unterschritten wird.

---

Ich regel und steuere meine WP quasi komplett über HA, da die interne Steuerung extrem schlecht mit meinem Passiv/3L-Haus funktioniert. Ich erzwinge eine mindest Laufzeit von einer Stunde und am Ende vom Heizen prüfe ich ob Warmwasser benötigt wird. Damit habe ich meine Arbeitszahl von ~2,3 auf ~4,5 gebracht. Des weiteren habe ich viel weniger Impulse und damit weniger Verschleiß.

**Comment by kroessig** [comment]
Hallo BenPru,

die Einstellungen sind noch vom Vorbesitzer ohne smarte Steuerung. Ehrlich gesagt, habe ich diesen Punkt och nicht hinterfragt gehabt. Din zweiter Absatz klingt aber logisch.... werde dem demnächst nachgehen. 
Und falls die Anmerkung kommt, ich habe nur einen großen Heizkörper und steuere die Haustemperatur bereits komplett über die Heizkurve.... Meine Laufzeit liegt aktuell zwischen 2-6h am Stück, die restliche Zeit ist "Ruhe"

**Comment by rhammen** [comment]
Have look at https://github.com/BenPru/luxtronik/issues/226#issuecomment-1881978225
Setting the operation mode to 'performance' (without the '')  in this way will set the operation mode to Party, and thus the heatpump will start heating the domestic water using the heatpump even during bock time.

**Comment by rhammen** [comment]
@kroessig Did you try my suggestion? Is your problem now solved?

**Comment by kroessig** [comment]
i have not tested that suggestion completely. But it's sounds good. I can change the operation mode with the mentioned service.

thanks a lot for that explanation.

**Comment by morpeuse** [comment]
hey I have the same requirement but one point. If I have the blocking time active, than is also the performance mode not enough. So I need the fast charging mode (Schnellladung). 
I have test it and the domestic water pump don't start.
