### ISSUE TITLE
Add long-term statistics

### ISSUE THREAD

**Issue by Alkaramazov** [BenPru/luxtronik#204]
I tried to add DHW temperature on a dashboard statistics graph card. But I were not able to find a temperature sensor there.
It seems that explanation is here : https://www.home-assistant.io/more-info/statistics/

**Comment by BenPru** [comment]
I have added it.
Please try the main branch.

**Comment by Alkaramazov** [comment]
Yes indeed, I can add it on a dashboard now ! Thanks a lot !
Since it seems to be a single line to edit, may I suggest to add every temperature sensor usable in the statistics ? Even the "numeric value" if it's possible, like "DHW target temp"
I do not need another one yet, but maybe other people do ...
Thanks

**Comment by BenPru** [comment]
I add the other in a future release.
