### ISSUE TITLE
sensor.warmequellen_eintrittstemperatu

### ISSUE THREAD

**Issue by Laemmchen1780** [BenPru/luxtronik#205]
Hi BenPru, 
best regards to Kleve. 

Will these sensors also be available in future ? 

**[sensor.warmequellen_eintrittstemperatur]
Wärmequellen-Eintrittstemperatur

[sensor.warmequellen_austrittstemperatur]
Wärmequellen-Austrittstemperatur**

It is perfect to calculate the heat pump performance coefficient (COP)

Thank you.

**Comment by BenPru** [comment]
See
sensor.luxtronik*_heat_source_input_temperature calc 19 ID_WEB_Temperatur_TWE
sensor.luxtronik*_heat_source_output_temperature calc 20 ID_WEB_Temperatur_TWA
But
calc 20 ID_WEB_Temperatur_TWA
is not available in every heatpump. For example my LAD 7 always sends -50.0 for this sensor.

**Comment by colognebroker** [comment]
for me it is : sensor.luxtronik_XXX_heat_source_input_temperature
and
 sensor.luxtronik_XXX_heat_source_output_temperature ??
