### ISSUE TITLE
T-WQ min to set in HA

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#207]
Would it be possible to make this Parameter to see in HA
and to change it ?
This is Temerature Minimum for S0urce Temp?

**Comment by BenPru** [comment]
Do you know which param it is?

**Comment by colognebroker** [comment]
hm i try to find

**Comment by colognebroker** [comment]
93: Unknown("ID_Einst_TWQmin_akt"),
this is the parameter
your implementation helps really so much thanks for that

**Comment by BenPru** [comment]
> 93: Unknown(\"ID_Einst_TWQmin_akt\"),

Great, thanks.
Is the unit C° or Kelvin?
0.5 as Step?

**Comment by colognebroker** [comment]
It is C
Step 0,5 yes

**Comment by colognebroker** [comment]
if you implement this would be nice to see code diff so that i can use it

**Comment by colognebroker** [comment]
yes this is true but nor realistic
because the heatpump ist only effective till -9 C

**Comment by BenPru** [comment]
I have added it. Please try the main branch.

**Comment by colognebroker** [comment]
i use 
2023.11.12-Beta
you mean this ?

**Comment by BenPru** [comment]
No. You can choose "main":
![image](https://github.com/BenPru/luxtronik/assets/32298537/a2a814f4-bbe6-459f-aebb-e770302459de)

**Comment by colognebroker** [comment]
many thanks

**Comment by colognebroker** [comment]
worked everything is fine
