### ISSUE TITLE
The German language for the settings is missing

### ISSUE THREAD

**Issue by SchBenedikt** [BenPru/luxtronik#209]
![image](https://github.com/BenPru/luxtronik/assets/137323528/a917078c-b3a3-4961-9f0e-d004639bce7c)
Hello!
It seems that when I install this with German language, the HomeAssistant settings don't show the translations.

**Comment by BenPru** [comment]
Have you restarted Home Assistant after installing via HACS?
Please check the log for luxtronik entries and post it in this issue.

**Comment by SchBenedikt** [comment]
@BenPru 
Unfortunately I don't have a log message, but I do have the solution to the problem:
My system language was set to German. I have now reset this to English and then set it back to German and restarted - now the entire description is displayed.
But thanks anyway for the help!
