### ISSUE TITLE
Frage: Automatisierungen

### ISSUE THREAD

**Issue by SchBenedikt** [BenPru/luxtronik#211]
Ich stelle diese Frage jetzt einfach auf Deutsch:

Könnte ich nach einer Einbindung von einer Alpha Innotec Wärmepumpe diese auch über Automatisierungen mit HomeAssistant direkt steuern? Also beispielsweise einen Wert auslesen (mit Weidemann Lesekopf) und bei einem bestimmten Wert dann die Wärmepumpe starten?
Vielen Dank schon mal im Vorraus,
schBenedikt

**Comment by BenPru** [comment]
> Könnte ich nach einer Einbindung von einer Alpha Innotec Wärmepumpe diese auch über Automatisierungen mit HomeAssistant direkt steuern? 

Ja, wenn die WP einer Luxtronik 2.x Firmware/Steuerung hat.

> Also beispielsweise einen Wert auslesen (mit Weidemann Lesekopf) und bei einem bestimmten Wert dann die Wärmepumpe starten?

Nahezu alle Werte die die WP hat, können über die Integration ausgelesen werden.
Und auch nahezu alle Funktionen können schreibend angesprochen werden.
Natürlich auch in Automatisierungen. Nutze dazu die steuernden Elemente climate.*, water_heater.*, switch.* oder number.*.
z.B.
climate.luxtronik*_heating
switch.luxtronik*_heating

Mit Weidemann Lesekopf meinst Du einen IR-Schreib-Lesekopf am Stromzähler?

**Comment by SchBenedikt** [comment]
Ja - genau den meine ich. (An einem digitalen Stromzähler)
