### ISSUE TITLE
no devices or entities

### ISSUE THREAD

**Issue by NL-TCH** [BenPru/luxtronik#212]
Hey everyone,

thanks for this integration, but two things:
1. my heatpump is not auto detected (alfa innotec)
2. when manually adding the heatpump, there are no devices or entities detected

(using v 2023.03.24 on my raspberry pi)

**Comment by BenPru** [comment]
Which HA version.
Please notice the readme.
The last stable integration is only working with HA <2023.8.*!
For HA >=2023.8.* use the latest beta.

**Comment by NL-TCH** [comment]
ip details of the heatpump:
```
eth0      Link encap:Ethernet  HWaddr 40:EC:F8:03:A1:22  
          inet addr:192.168.178.21  Bcast:192.168.178.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:375182 errors:23 dropped:0 overruns:0 frame:0
          TX packets:29315 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:25121359 (23.9 MiB)  TX bytes:5686264 (5.4 MiB)
``` 
kernel details: `Linux (none) 2.6.17.7-fs.1 #19 Tue Aug 4 17:13:45 CEST 2009 armv5tejl unknown`

**Comment by NL-TCH** [comment]
> Which HA version. Please notice the readme. The last stable integration is only working with HA <2023.8._! For HA >=2023.8._ use the latest beta.

ah, thanks!
maybe another stupid question, how do i enable the beta version?
