### ISSUE TITLE
Issue: heat_amount_heating unusual spikes

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#215]
Hi, 

as you can see in the picture below, I've got an unusual spike in sensor.luxtronik_*****_heat_amount_heating. 

It is rising when heating starts and after heating stopped, it is set back to an earlier value. That behavior is a problem to my utility meters. 

I'm not sure why this happens, but it is not the first time. 

<img width="1290" alt="image" src="https://github.com/BenPru/luxtronik/assets/4194672/600c0c39-ee16-4bb9-8366-1660fc30c31c">

**Comment by BenPru** [comment]
Can you try and check a shorter [update-interval](https://github.com/BenPru/luxtronik/blob/ab3888a53234dd2d60b813699bbc1b5237efc016/custom_components/luxtronik/sensor_entities_predefined.py#L514)?

**Comment by Crashman1983** [comment]
Yes I will try that. But today I saw a new spike, really big one: 26,4 vs 36,1 kWh.


coincidentally I was near the luxtronic when this happened and what I saw was a little surprising: a sudden luxtronik reboot. That may be another wie source - but Heat Pump stopped and started again - that is not the same behavior .
