### ISSUE TITLE
Heat Amount heating / dhw: Difference between sensor value and luxtronik web portal

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#217]
Luxtronik integration does report 

heat_amount_heating
![image](https://github.com/BenPru/luxtronik/assets/4194672/ce189dcf-4c41-40ed-88f0-f261574bed5a)

dhw_heat_amount
<img width="555" alt="image" src="https://github.com/BenPru/luxtronik/assets/4194672/ed560a61-617d-435b-aac7-8d7fdcb82f92">

Total heat amount is not reported, but can be calculated within HA using a template sensor. 

When I compare these sensor values with values from luxtronik web interface, I can see a gap.

<img width="740" alt="image" src="https://github.com/BenPru/luxtronik/assets/4194672/eb0f89eb-0f2e-40e9-92b2-6b721a9cf237">

Where is this difference coming from?

**Comment by Mehli12** [comment]
Same here.
But just for heat amount.

![Bildschirmfoto 2023-12-14 um 18 26 57](https://github.com/BenPru/luxtronik/assets/91239418/c8ee6e36-ac64-4f81-9ee7-2b5f441192d5)


![Bildschirmfoto 2023-12-14 um 18 27 27](https://github.com/BenPru/luxtronik/assets/91239418/6dc8be53-b2d8-4fea-abb0-9e35b8a5a139)

**Comment by BenPru** [comment]
In my case (Novelan LAD 7) the "input energy" sensors are updated delayed by the socket interface. Not sure if the websocket is faster.
Can you check it with another software (e.g. App) which uses also the socket interface?
Is the delay in the firmware (socket) or in the integration.
You can also play around with the [update-interval](https://github.com/BenPru/luxtronik/blob/ab3888a53234dd2d60b813699bbc1b5237efc016/custom_components/luxtronik/sensor_entities_predefined.py#L514).
