### ISSUE TITLE
Installation: No Devices and Entities found

### ISSUE THREAD

**Issue by Robman1** [BenPru/luxtronik#218]
Dear all,

thank you @BenPru for this excellent and easy to use integration. However I face the problem that afer the configuration "No devices and entities" are found.

![grafik](https://github.com/BenPru/luxtronik/assets/112414636/ff2f2bef-bbd5-4b7c-af74-115228640d04)

Configuration:
Home-Assistant installation in docker (Portainer), latest Version 2023.12.3
Heatpump: Alpha Innotec SWC 100 H/K, latest Firmware V1.88.3
Installation via HACS according to manual.

The connection seems to be establisehd since if I use a wrong IP address and port I get an error message. The webserver of the heatpump is avialable as well.

Any hints are highly welcome.

Thank you all.

**Comment by BenPru** [comment]
Which integration version?

**Comment by Robman1** [comment]
> Which integration version? **2023.02.02**

Any Luxtronik messages in the HA log? **No Luxtronik related messages in Logbook**

Please provide a Diag file as attachment in this issue. **Attached**
[config_entry-luxtronik2-193e293072d8ede884db7eca45cc5449.json.txt](https://github.com/BenPru/luxtronik/files/13689451/config_entry-luxtronik2-193e293072d8ede884db7eca45cc5449.json.txt)

**Comment by BenPru** [comment]
> 2023.02.02

This version is only compatible with HA<2023.8.*!
Please use older HA or a newer integration. The latest beta.

**Comment by Robman1** [comment]
Problem solves by using the latest Beta. [2023.11.30-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.11.30-Beta)
Thank you @BenPru for the promt answer
