### ISSUE TITLE
Add warmwater and heating counter

### ISSUE THREAD

**Issue by Gifford47** [BenPru/luxtronik#221]
For automations would it be very helpful if there's an extra attribute under the heat pump status which counts the number of warmwater or heating cycles per 24h. The counter could be resetted at midnight. 
In my case I have to limit the number of cycles per day.

**Comment by BenPru** [comment]
See #187 
Planned and started to work on it, but I don't have enough time to force it. I think it comes after the current heat period.

**Comment by Gifford47** [comment]
nice, thanks for the awesome project!
is there a discord channel, i want to contribute to this project, but i have some questions before.
