### ISSUE TITLE
Add additional parameters to integration with version 2023.11.30

### ISSUE THREAD

**Issue by Robman1** [BenPru/luxtronik#225]
Dear @BenPru, dear all,

I've tried to add additional paramters like 

ID_WEB_Temperatur_TWE Wärmequellen-Eintrittstemperatur
ID_WEB_Temperatur_TWA Wärmequellen-Austrittstemperatur

with the following entry in configuration.yaml

sensor:
  - platform: luxtronik2
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TWE
        friendly_name: Waermequellen-Eintrittstemperatur
        icon: mdi:thermometer

As a result I get the following Message after restarting HA 2023.12.4:

![grafik](https://github.com/BenPru/luxtronik/assets/112414636/d8e7b4f2-dc63-4251-b78b-903c4eea5335)

Any hint how to integrate additional sensors?
Thank you.

BR
Robert

[config_entry-luxtronik2-d32a57824ae1c07b3cb3c80a43353220.json.txt](https://github.com/BenPru/luxtronik/files/13805197/config_entry-luxtronik2-d32a57824ae1c07b3cb3c80a43353220.json.txt)

**Comment by BenPru** [comment]
See [the documentation](https://github.com/BenPru/luxtronik?tab=readme-ov-file#32-additional-sensors-advanced). YAML config is nor more supported in the newer versions.

> ID_WEB_Temperatur_TWE Wärmequellen-Eintrittstemperatur

See sensor.luxtronik*_heat_source_input_temperature

> ID_WEB_Temperatur_TWA Wärmequellen-Austrittstemperatur

See sensor.luxtronik*_heat_source_output_temperature
