### ISSUE TITLE
Service to switch between BW Modes missing / unknown Error in "Turn on/off BW Brauchwasser"

### ISSUE THREAD

**Issue by Robman1** [BenPru/luxtronik#226]
Dear @BenPru and community,

how can I create an automatization which allows to switch the BW modes? E.g. I would like to switch between "Heat Pump" and "Performance" (=Party) Mode within an automatization.

![grafik](https://github.com/BenPru/luxtronik/assets/112414636/0d46242f-38d4-4add-aebd-300edfa8ba60)
![grafik](https://github.com/BenPru/luxtronik/assets/112414636/395e319c-5026-4d95-8d0d-c64b9ddc9353)

I also realized that the two actions marked in red lead to "unknown Error" when executed
![grafik](https://github.com/BenPru/luxtronik/assets/112414636/a511eac0-8e7a-4cbe-be2f-b36acde8be3e)

I am using the 2023.11.30-Beta

One may excuse my novice question(s) but I am pretty new to the HA topic. Thank you for your patience.

Best regards
Robert

**Comment by rhammen** [comment]
I'm on HA 2024.1

In the automations dialog:
Then-do:
     Service: Water Heater: Set operation mode
     Targets: DHW Dometic Water
     operation mode: heat_pump, performance, electric or off

**Comment by rhammen** [comment]
@Robman1 Did you try my suggestion? Is your problem now solved?

**Comment by Robman1** [comment]
@rhammen: thank you for the hint. Your proposal would have been more elegant since it uses the UI. In the end I've used the "write" service directly. In the end it is the same. Thank you for your support.
