### ISSUE TITLE
new heat pump version V3.89.4-10229 

### ISSUE THREAD

**Issue by KlausV66** [BenPru/luxtronik#229]
Hi,
I would like to update my heat pump to the newest version V3.89.4-10229. Can someone confirm to run without any problems, especially for the home assistant integration?
Thanks.
Klaus

**Comment by kairetzlaff** [comment]
> Hi, I would like to update my heat pump to the newest version V3.89.4-10229. Can someone confirm to run without any problems, especially for the home assistant integration? Thanks. Klaus

Hi, I have it installed since 2 weeks and there is no issues in regards to HA.

**Comment by Crashman1983** [comment]
no issues so far
