### ISSUE TITLE
How to read used energy of luxtronik heatpump

### ISSUE THREAD

**Issue by fzzybllz** [BenPru/luxtronik#230]
Hi,
I am using this integration in HA with my luxtronik heatpump.
In the web interface of my heatpump I can find information about the used energy for heating and hot water.

Is it possible to read this information in HA?

So far I was just able to find the "produced energy"

**Comment by kairetzlaff** [comment]
> Hi, I am using this integration in HA with my luxtronik heatpump. In the web interface of my heatpump I can find information about the used energy for heating and hot water.
> 
> Is it possible to read this information in HA?
> 
> So far I was just able to find the "produced energy"

You can add widget "Dignose" from integration to your dashboard.. It is in "Devices", "Heiz" .

**Comment by fzzybllz** [comment]
Hi @kairetzlaff 
could you add a screenshot of that widget?
I cannot find it.
thanks

**Comment by kairetzlaff** [comment]
> Hi @kairetzlaff could you add a screenshot of that widget? I cannot find it. thanks

![WP_](https://github.com/BenPru/luxtronik/assets/92909733/b2188cbe-f158-4034-a853-33de6de3ce94)

**Comment by fzzybllz** [comment]
Interesting, I miss the entire diagnostic widget for all three devices (Heat, DHW, HP).

**Comment by fzzybllz** [comment]
Found the issue, the version of my integration was old. Update fixed it
