### ISSUE TITLE
manual installation required, no devices or entities found

### ISSUE THREAD

**Issue by dmm1** [BenPru/luxtronik#231]
Hi, i wanted to switch to this integration;
there was no auto-config, the manual worked but no devices or entities found.
![image](https://github.com/BenPru/luxtronik/assets/343625/32f70d8f-fe5a-42a9-bdbd-cff8a2191456)

When you download the current diagnostics, there are correct values in it:
![image](https://github.com/BenPru/luxtronik/assets/343625/357e876a-530a-4c97-aa4f-2bb408c20b80)
Do you have an idea? 
Thanks in advance

**Comment by BenPru** [comment]
If you use HA >= 2023.8 please ensure to use the latest prerelease of this integration.
Please read the readme of the latest prerelease.

**Comment by dmm1** [comment]
thanks, it works now!
