### ISSUE TITLE
Entities not here - after successfull installation & configuration 

### ISSUE THREAD

**Issue by ChristophDramski** [BenPru/luxtronik#232]
Hello @BenPru,
sorry for disturbing you at saturday evening :-(
Can you help me with my issue on luxtronik side?
[home-assistant_luxtronik2_2024-01-20T17-46-15.274Z.log](https://github.com/BenPru/luxtronik/files/13998850/home-assistant_luxtronik2_2024-01-20T17-46-15.274Z.log)
 Thanks a lot for your help :-)

Best regards,
Christoph

**Comment by BenPru** [comment]
Which HA Version?
Which integration version?

**Comment by ChristophDramski** [comment]
Ahhh now I see this problem 😣 I am using HA Core 2024.1.4 and HAOS 11.3. Integration is 2023.03.08. I suppose my HA is not supported 😔

**Comment by morpheus12** [comment]
Same Issue here. Using HA Core 2024.1.5 and HAOS 11.4 with the newest Version of Luxtronic 2.

I tried port 8888 and got an unknown error while integration. With Port 8889 i receive a successfull message but without any entities.

**Comment by BenPru** [comment]
If you use HA 2023.8.* or higher, please use the latest beta integration version.

**Comment by morpheus12** [comment]
> If you use HA 2023.8.* or higher, please use the latest beta integration version.

Hi Benpru, thx for fast reply. 
is it necessary to register the heatpump in the alpha Innotec/ Novelan cloudportal (heatpump24.com)? I’ve seen that the integration tried to fetch data from there but didn’t received anything. 

I’ll test again with the beta. Can we support anyway?

**Comment by BenPru** [comment]
> is it necessary to register the heatpump in the alpha Innotec/ Novelan cloudportal (heatpump24.com)? 

No.

> I’ve seen that the integration tried to fetch data from there but didn’t received anything.

Yes, it connects to the download folder on the server to detect the latest online firmware version.

**Comment by BenPru** [comment]
@morpheus12 @ChristophDramski Can we close this issue?

**Comment by ChristophDramski** [comment]
Hi. Yes. It works fine! Thanks a lot for your help and effort @BenPru  :-)

**Comment by morpheus12** [comment]
Hi @ChristophDramski, 
could you assist me how to download/integrate correctly the latest beta? I'm too stupid for that. I guess by following the instructions (add repository to hacs => download it to HA) i get the official release version. Thx

**Comment by morpheus12** [comment]
Still the same
![grafik](https://github.com/BenPru/luxtronik/assets/23457727/a2637a01-2782-4e47-8d92-1595c513cd43)

I was able to integrate with Port 8889 but afterwards no entities.
