### ISSUE TITLE
Heat amount decreasing, but state_class is total_increasing

### ISSUE THREAD

**Issue by ChrisMisker** [BenPru/luxtronik#235]
The sensor heat_amount_heating has a state_class of "total_increasing", but sometimes I see a decrease in the amount of heat generated. That's strange, isn't it? Seems like that shouldn't be possible. 
<img width="1160" alt="Scherm­afbeelding 2024-02-01 om 09 45 00" src="https://github.com/BenPru/luxtronik/assets/37826263/1a7342a9-0426-40a0-9d40-41a4970ab2e5">
<img width="1160" alt="Scherm­afbeelding 2024-02-01 om 09 46 25" src="https://github.com/BenPru/luxtronik/assets/37826263/3208b07f-3a20-4d15-a571-8f89e3c0321c">

**Comment by BenPru** [comment]
Please connect an USB-Stick to your heatpump and activate the data logger.
Then look into it and validate that the peaks are not in the data from the Luxtronik data logger.

**Comment by ChrisMisker** [comment]
Another strange thing happened last night:
<img width="1184" alt="Scherm­afbeelding 2024-02-13 om 10 35 21" src="https://github.com/BenPru/luxtronik/assets/37826263/26a76293-a82e-4c12-a372-e55754044436">

I have the datalogger downlad, but no idea what to do with it.

**Comment by BenPru** [comment]
> Can you point me in the right direction?

You should find three files: DTA+CSV+ERR
The CSV can you open with Excel.
See also:
https://www.youtube.com/watch?v=9cUT0Vh4x2Y
https://www.haustechnikdialog.de/Forum/t/174914/Luxtronik-II-Datenlogging

**Comment by Kars-de-Jong** [comment]
Are you sure your heat pump controller hasn't restarted? I have seen several people on a german forum report crashes with version 3.89.x of the firmware.

**Comment by Crashman1983** [comment]
With the current firmware (don't know if that was the case before) the Heatpump seams to "correct itself". Another situation where a decrease can be seen, is during deicing (Abtauen). Seems to be normal. My Luxtronik is crashing is well and sometimes it destroys my statistics.
