### ISSUE TITLE
Root access to Luxtronik

### ISSUE THREAD

**Issue by rcreate** [BenPru/luxtronik#236]
Not really an issue but a very interesting chance to get more details and opportunities. 
today, I read an article on heise.de that for heatpumps below 2.88.3 (and other types, too) root access is possible. The password was leaked there. It is „eschi“. You can read the article here: https://www.heise.de/news/Waermepumpen-von-Alpha-Inntotec-und-Novelan-mit-hardkodiertem-Passwort-9618846.html

I thought you all would be interested to discover your devices and find out more hidden stuff. When I have time, I’ll do this, too. 

Looking forward for the next update ;-)

**Comment by rcreate** [comment]
Btw… don’t make your heatpump accessible to the public! Can be dangerous and cold if someone destroys your device 😉

**Comment by BenPru** [comment]
Yes, you can get a root shell. But as I know you don't need a password for this.
The Socket is also not password protected.
So you should never forward your heatpump to the internet.

**Comment by BenPru** [comment]
> you know how to get into the shell

But it is years ago that I have tried it. So perhaps it is closed or changed in the current versions.
