### ISSUE TITLE
Daily heat amount

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#24]
Could we have a sensor, that compares heat energy (kWh) day by day?

**Comment by Kars-de-Jong** [comment]
You can create that yourself by adding a utility meter helper with a daily cycle.

**Comment by Crashman1983** [comment]
thx, did not know that such thing exists :-)

**Comment by BenPru** [comment]
Alternativ you can add the value very simple to the energy dashboard. This creates daily stats automaticly.

**Comment by Kars-de-Jong** [comment]
Right, I didn't think of putting "heat" entities in there, I just put electrical energy in there ;-)
