### ISSUE TITLE
homeassistant.util.async_

### ISSUE THREAD

**Issue by djm193** [BenPru/luxtronik#240]
Logger: homeassistant.util.async_
Source: util/async_.py:141
First occurred: 17. Februar 2024 um 13:42:15 (4 occurrences)
Last logged: 11:21:45

Detected blocking call to sleep inside the event loop by custom integration 'luxtronik2' at custom_components/luxtronik2/lux_helper.py, line 279: time.sleep(WAIT_TIME_WRITE_PARAMETER), please create a bug report at https://github.com/BenPru/luxtronik/issues

**Comment by rhammen** [comment]
See #39
