### ISSUE TITLE
Add Missing Sensors (Outdoor Temperature, flow in/out temperature)

### ISSUE THREAD

**Issue by Albert994** [BenPru/luxtronik#243]
Hello,

I updated from the 2023.03 version. I miss some sensors. Could you please add them. (The sensor circulation_pump_heating I found in the list of deactivated sensors, the others unfortunately not):
- outdoor_temperature
- outdoor_temperature_average
- flow_out_temperature
- flow_out_temperature_target
- flow_in_temperature ("Vorlauf", I'm not sure about the sensor name

Thanks
Albert

**Comment by BenPru** [comment]
Please ensure the latest beta integration if you use HA 2023.8 or higher.

**Comment by Albert994** [comment]
I have selected yesterday the main branch. That should be the latest version, or?

**Comment by Albert994** [comment]
[home-assistant_2024-02-28T06-10-56.037Z.log](https://github.com/BenPru/luxtronik/files/14429604/home-assistant_2024-02-28T06-10-56.037Z.log)

This is my log file. Does this give any hints?

**Comment by BenPru** [comment]
@Albert994 Please try now the main branch.

**Comment by Albert994** [comment]
@BenPru : Works with the fix. Thanks!
