### ISSUE TITLE
is_aux_heat warning

### ISSUE THREAD

**Issue by AJediIAm** [BenPru/luxtronik#245]
![Screenshot_20240329-132348](https://github.com/BenPru/luxtronik/assets/5879533/078d04ca-0262-471b-af69-008819a2ebb4)

is_aux_heat will be deprecated in 2024.10
This warning is shown since 2024.4.0b0

To users who encounter this issue and who are looking for a solution: you can safely ignore the warning. Everything still works as it should.

**Comment by rhammen** [comment]
We're approaching the end of September. It won't be long till people start installing HA 2024.10.0 ...
@BenPru What is the plan/planing? Are you working on a new release? Can we help in some way, e.g. testing the new version? Or have you given up on this project?

**Comment by BenPru** [comment]
> We're approaching the end of September. It won't be long till people start installing HA 2024.10.0 ... @BenPru What is the plan/planing? Are you working on a new release? Can we help in some way, e.g. testing the new version? Or have you given up on this project?

My plan was to work on it last weekend... But the children were outsourced, the weather was great, the open-air music festival in town was fabulous, the alcohol too much and the weekend too short. 🙈😅
I try to release it this week. Testing would be great.

**Comment by BenPru** [comment]
@rhammen Can you test [2024.9.23-Beta](https://github.com/BenPru/luxtronik/releases/tag/2024.9.23-Beta)?

**Comment by rhammen** [comment]
Happy to see you working on a new release, great!
Testing 20249.23-Beta now...

1) The is_aux_heat warning is gone --> 👍 

2) The following warning (as reported in #255 item 6) is still present:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:363
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 22:12:07 (2 occurrences)
Last logged: 22:12:07

    Entity climate.luxtronik2_heating (<class 'custom_components.luxtronik2.climate.LuxtronikThermostat'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/BenPru/luxtronik/issues
    Entity climate.luxtronik2_cooling (<class 'custom_components.luxtronik2.climate.LuxtronikThermostat'>) implements HVACMode(s): cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/BenPru/luxtronik/issues

3) The following warning (as reported in #255 item 7) is still present:
(in #255 it is suggested that changing in base.py
from homeassistant.backports.enum import StrEnum--> from enum import StrEnum
fixes this issue)

Logger: homeassistant.backports.enum
Source: helpers/deprecation.py:206
First occurred: 22:12:06 (1 occurrences)
Last logged: 22:12:06

StrEnum was used from luxtronik2, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'luxtronik2' custom integration

**Comment by BenPru** [comment]
@rhammen Can you test the new beta [2024.9.28-Beta](https://github.com/BenPru/luxtronik/releases/tag/2024.9.28-Beta). 2 + 3 should also be fixed.

**Comment by rhammen** [comment]
> @rhammen Can you test the new beta [2024.9.28-Beta](https://github.com/BenPru/luxtronik/releases/tag/2024.9.28-Beta). 2 + 3 should also be fixed.

I updated to 2024.9.28-Beta on HA 2024.9.2
The warnings 2+3 are gone, so everything looks good to me!
Thanks for your effort on updating this integration!
