### ISSUE TITLE
 `is_aux_heat` property or uses the auxiliary heater methods is deprecated 

### ISSUE THREAD

**Issue by Freakandel74** [BenPru/luxtronik#250]
Since the latest update of HA (version 2024.4.x) the luxtronic component is giving an error:

The custom integration luxtronik2 implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity.

Full log:
Logger: homeassistant.components.climate
Bron: components/climate/__init__.py:419
integratie: Klimaat (documentatie, problemen)
Eerst voorgekomen: 11 april 2024 om 15:49:47 (1 gebeurtenissen)
Laatst gelogd: 11 april 2024 om 15:49:47

luxtronik2::LuxtronikThermostat implements the `is_aux_heat` property or uses the auxiliary heater methods in a subclass of ClimateEntity which is deprecated and will be unsupported from Home Assistant 2024.10. Please create a bug report at https://github.com/BenPru/luxtronik/issues

**Comment by BenPru** [comment]
It is not an Error, it is a warning and have to fix till 2024.10.*

**Comment by BenPru** [comment]
See #245
