### ISSUE TITLE
ZWE operating mode with photovoltaic surplus

### ISSUE THREAD

**Issue by TechSaiyajin** [BenPru/luxtronik#257]
Hello,

I would like to activate the heating rod (ZWE1) when there is a photovoltaic surplus.

Is there a way to switch between automatic and ZWE operating mode via automation?

Greetings from Germany

**Comment by BenPru** [comment]
I think this souhld work:
For **heating**:
Set **climate.luxtronik*_heating**
- **.state = heat** (hvac_mode) and
- **.preset_mode = boost** and
- **.temperature** > (.current_temperature + number.luxtronik*_heating_hysteresis)

For **Domestic Water**
Set **water_heater.luxtronik*_domestic_water**
- **.state = electric** (operation_mode) and
- **.temperature** > (.current_temperature + number.luxtronik*_dhw_hysteresis)

**Comment by TechSaiyajin** [comment]
That works, thank you very much!
