### ISSUE TITLE
Read error in node Red

### ISSUE THREAD

**Issue by PVAnfaenger** [BenPru/luxtronik#258]
Hello,
I have installed the Luxtronic2 addOn in Node Red. So far everything is working, except after I have written a value to the Red heat pump firmware R1.77, the read node, which I currently trigger manually for 2-3 read starts, does not work. I get the feedback that it is busy! If I want to automate the reading later and perhaps run it every 30 minutes, I would like to check whether the reading process was successful, how can I do this?

![NodeRedDebug](https://github.com/BenPru/luxtronik/assets/147447750/5f7ed717-d747-47df-ab6c-54fdb67101d3)

I am currently trying this with a function node, and thought I would simply restart the read process in the event of an "error". But that doesn't always work, from my feeling I would say that the error doesn't occur so often anymore, but I can't prove that is just a feeling.

![NodeRedDebugFunktionNode](https://github.com/BenPru/luxtronik/assets/147447750/adbfe55b-5113-4d72-973d-874c2536fc3e)

Best regards
PV_Anfänger

**Comment by BenPru** [comment]
This Repo is only for Home Assistant not for node red.
