### ISSUE TITLE
Autodiscovery not working. No devices and no entities found.

### ISSUE THREAD

**Issue by nibi2299** [BenPru/luxtronik#265]
Hi

I'm trying to work with the integration. Installation was successful, but autodiscovery didn't work. I added it manually but now it shows no devices or entities.
![2024-08-18_11h58_56](https://github.com/user-attachments/assets/0a43883e-eb84-46ef-a1b9-4928b1c6d889)

**Device Information:**
**Manufacturer**: Alpha Innotec
**Model**: LWC 120
**Controller**: Luxtronic, Softwareversion: V1.88.3, Revision: 9717
**MAC**: 40:EC:F8:0C:05:E3
**Homeassistant:** 
Core 2024.8.2
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240809.0

Debug protocol:
[home-assistant_luxtronik2_2024-08-18T09-48-21.568Z.log](https://github.com/user-attachments/files/16647942/home-assistant_luxtronik2_2024-08-18T09-48-21.568Z.log)

Diagnostics:
[config_entry-luxtronik2-01J5JE68NC625VVWS3NKF9V3ND.json](https://github.com/user-attachments/files/16647940/config_entry-luxtronik2-01J5JE68NC625VVWS3NKF9V3ND.json)

I also tried the integration from Bouni. It worked. I could read the sensors and write parameters back to the LWC 120.

Thanks for your help

nicola

**Comment by rhammen** [comment]
You are using an old Luxtronik version in combination with a recent HA core version. That combination will not work.
1) In HACS, go to the Luxtronik integration 
2) using the 3 dots in the upper right corner, select "Redownload"
3) Enable the "Show Beta versions"
4) Download 2024.01.10-Beta

**Comment by nibi2299** [comment]
Thank you. It worked.
I appreciate your help
![Screenshot 2024-08-19 212049](https://github.com/user-attachments/assets/43a9366e-0f9a-4ce1-b115-e23870e46840)

**Comment by XYP-1761** [comment]
Bei mir funktioniert das nicht.
Alpha Innotec SW 302H3, 2 Anlagen Master und Slave Betrieb.
Beide mit Firmware 3.90.0
Home Assistant 2024.9.3
Luxtronik 2024.9.23-beta
Es zeigt mir nach dem Update immer weniger Sensoren an und ich kann die Werte nicht mehr verändern.
![Unbenannt2](https://github.com/user-attachments/assets/3e84d7dc-ae07-431a-bae9-0d347cfabbbf)
![Unbenannt](https://github.com/user-attachments/assets/02453ef1-9caa-453b-a9f8-e51bc0043795)
Was kann ich hier machen, damit das wieder funktioniert?

**Comment by BenPru** [comment]
@XYP-1761 Please provide a Diag file as comment attachment and you should have luxtronik messages in your HA log. See documentation how to create the file.

**Comment by XYP-1761** [comment]
[config_entry-luxtronik2-43bdfd42d83125d6bcb9a01e414137c3.json](https://github.com/user-attachments/files/17165562/config_entry-luxtronik2-43bdfd42d83125d6bcb9a01e414137c3.json)
[config_entry-luxtronik2-d157a709e24aa63aae98e21a8a0dfcf7.json](https://github.com/user-attachments/files/17165563/config_entry-luxtronik2-d157a709e24aa63aae98e21a8a0dfcf7.json)

**Comment by XYP-1761** [comment]
Hier meine Diagnosedateien.

**Comment by BenPru** [comment]
Unfortunately I have never finalized the upgrade steps from the last stable to the current beta version.
This is the primary reason why the beta is not yet final and I urge you to make a backup before upgrading from stable to beta.
One migration step is to change the unique ids from "luxtronik" to "luxtronik_%serialnumber%" to use the integration with more than one heatpump.
In your case the migration is failed. The heatpump with serial *395 have the correct unique id *395 but all regarding sensors have the wrong id *390. So their sensors have the same id as the sensors from your other heatpump with serial *390! And one or perhaps both of the double sensors are the losers at the home assistant startup and are deactivated.
To fix this you can restore your backup from before the luxtronik beta integration version and have another migration try with the newest beta. Ensure that no other integration version is active while or after backup restore. With luck you doesn't lose your sensor history.
The alternative try is to delete the heatpump *395, restart home assistant and add it again. In this case you lose your sensor history for all sensors of this heatpump. If you need them you have to write your own sql migration script.
Sorry for this bad news.

**Comment by XYP-1761** [comment]
Vielen Dank für deinen Kommentar. Leider weis ich überhaupt nicht, wo ich die Angaben ändern soll. Im Moment bekomme ich einige Werte. Doch bis vor ein paar HA + Luxtronik Versionen, funktionierte alles einwandfrei. Ich konnte neben dem Auslesen von Sensoren auch Änderungen vornehmen, die dann auch schön übernommen wurden.
Ich habe sogar versucht, parallel eine alte HA + Luxtronik Version zu installieren, jedoch erfolglos.
Bin etwas überfordert und entäuscht, dass nicht mehr alles funktioniert. Ich wahr bisher hell begeistert.
Ich hoffe, dass mir jemand helfen kann der Lust und Zeit dafür hat.

**Comment by BenPru** [comment]
This ticket should be fixed with the new stable release.
