### ISSUE TITLE
Write error notification on parameters

### ISSUE THREAD

**Issue by stefanovich1** [BenPru/luxtronik#266]
Hello friends,

I get a error notification while changing parameters.
The parameters get changes though. 

"Die Aktion water_heater/set_operation_mode konnte nicht ausgeführt werden. Write: Error communicationg with device.

Any suggestions how to fix this?

<img width="420" alt="image" src="https://github.com/user-attachments/assets/06aeeefa-64ea-42c6-a7a2-56b993a1feae">

**Comment by ChrisMisker** [comment]
See here: https://github.com/BenPru/luxtronik/issues/259#issuecomment-2215487774
