### ISSUE TITLE
Update 2024-10-05-beta multiple sensors disappearing

### ISSUE THREAD

**Issue by Taijian** [BenPru/luxtronik#281]
Hi!

I am currently running version 2024-09-30 with great satisfaction and wanted to thank you for the timely update to the integration.

After getting the notification about 2024-10-05-beta I decided to try that out as well, but this resulted in about half my sensors and all my switches disappearing from the integration. I quickly reverted and everything is fine again, nothing of value lost, just wanted to let you know that - at least for me - there seems to be some problematic change in the latest beta.

**Comment by blue-bean** [comment]
After i did the update to 2024.10.05-beta i noticed also the effect after the first restart. After a second restart all sensors and switches are back.

**Comment by Taijian** [comment]
OK, weird - after the second restart the sensors did indeed come back...

So, everything fine!

**Comment by blue-bean** [comment]
Maybe this issue should be reopened. With 2024-10-05-beta sensos disappear sometimes with a restart and  - after another restart - come back.

**Comment by Taijian** [comment]
Yeah, you're probably right. I've had this thing pop up on about half of my restarts/updates of HA lately - the sensors disappear and need *another* restart to appear again.

**Comment by blue-bean** [comment]
It seems that this behaviour is not special for this luxtronik integration. I have also sensors of other integrations which disappear and come back. I've noticed this since using HA core 2024.10.

**Comment by Mehli12** [comment]
I tried the 2024-10-5 beta and HA 2024.10.3 after first restart some sensors disappeared. After second restart all sensor back again. I restarted for several times, every second time, some sensors are missing.

No issues with 2024-09-30 and HA 2024.10.3 on my working system. I tried also some restarts there.

**Comment by blue-bean** [comment]
I definitively have the behaviour with disappearing/reappearing sensors also with 2024.10.3 and core 2024.9.3.
