### ISSUE TITLE
additional Parameters

### ISSUE THREAD

**Issue by MichaelS1955** [BenPru/luxtronik#290]
Hi,
I miss these two values, "Heizleistung Ist" and "Leistungsaufnahme". Is it possible to ad them?

![image](https://github.com/user-attachments/assets/46b1fc8b-574e-4d0d-9353-aa63afa801aa)

Regards
Michael

**Comment by blue-bean** [comment]
The first one is present (sensor.luxtronik_xxxxxx_xxxx_current_heat_output).
Also the second one is present in the latest 2024.10.05 (current power consumption, see [Link](https://github.com/BenPru/luxtronik/commit/745256b50ad985155cf65b42fd9d4bd4551688f4)

**Comment by MichaelS1955** [comment]
thank you. I did not found the first value, because the measurement is different. Is there any reason for this?

I will install the beta.

**Comment by BenPru** [comment]
@MichaelS1955 I close the issue. Feel free to reopen it if needed.
