### ISSUE TITLE
Heathpump with password. How to connect?

### ISSUE THREAD

**Issue by ericbroers** [BenPru/luxtronik#295]
Hi,

When I connect to my heath pump with a browser, a password is needed for access. (see Pic1)

When I want to configure the Luxtronic integration, no password option is available. (see Pic2)

I tried to remove the password on my heath pump device, but without success.

Please advice.

Regards,
Eric

<img width="755" alt="Pic1" src="https://github.com/user-attachments/assets/172ee3ba-2fd9-46ff-b085-4bebac483c79">
<img width="751" alt="Pic2" src="https://github.com/user-attachments/assets/b4d074ba-6938-4cff-83b1-0ac641ef45a9">

**Comment by DerAutomatiker** [comment]
The password is not required for the integration to work.
