### ISSUE TITLE
Cant connect to heatpump 

### ISSUE THREAD

**Issue by aaronlutin** [BenPru/luxtronik#296]
When I try to connect with the heatpump I gett this error. Can someone help me fix this problem ?  As host name is use the IP adres of the heatpump and i tried both port numbers. 

![Schermafbeelding 2024-11-14 200145](https://github.com/user-attachments/assets/7497773c-db51-447a-a330-b65bec690974)

**Comment by BenPru** [comment]
Home assistant can't reach the ip address or hostname which you have inserted.
Please check your input and network connection.

**Comment by BenPru** [comment]
Runs your HA in the same system as your local Browser?
Normally not. So, please ensure that the Network between your HA Server and the Heatpump works.

**Comment by BenPru** [comment]
Ist something from Luxtronik in the HA logs?
Which Firmware Rev, HA and Integration Versions?

**Comment by PWDevelop** [comment]
I'm using Integration 2024.9.30 version. 
HA Core  is updated to latest one - 2024.11.2

As for the firmware let me check, I haven't updated it for a while but still previously it was working.

From logs I saw something strange, that an entry already exists, perhaps it was some bug during initial setup:

`Could not handle config_flow.async_step_options {'host': '192.168.0.225', 'port': 8889, 'timeout': 60, 'max_data_length': 10000}
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/config_flow.py", line 224, in async_step_options
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2633, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured`

I'll try to look how to remove this entry manually.

**Comment by PWDevelop** [comment]
ok never mind me. Seem like it was added however it was disabled just after adding it (not sure why). Anyway for me it works now just fine.
![image](https://github.com/user-attachments/assets/dad67a2d-8910-4cf9-93e5-2aa193313c34)

Perhaps similar issue is for @aaronlutin. check if the device was added and disabled automatically.

**Comment by aaronlutin** [comment]
> Runs your HA in the same system as your local Browser? Normally not. So, please ensure that the Network between your HA Server and the Heatpump works.

How can i check this ? I'm a noob at all of this. Is there a way to ping a IP adres from my virtual HA machine ? 

Btw the heatpump wasn't found by HA auto.  I read this note in the read me : 
"'If auto discovery does not work, please give feedback with the first six chars of your luxtronik heatpump mac address, the original hostname, the manufacturer and model." 

So here is some info about the heatpump: 

Its a Alpha Innotec WZSV 62K3M. 
*
![Schermafbeelding 2024-11-18 143759](https://github.com/user-attachments/assets/d2fa5e53-73a5-4408-a8b2-c1ec4244d6d2)
![Schermafbeelding 2024-11-18 143913](https://github.com/user-attachments/assets/db2a9839-9f4c-427a-b8f6-8a8bedf8c164)
![Schermafbeelding 2024-11-18 143942](https://github.com/user-attachments/assets/a5045afa-08f2-45fb-9c4c-aff016612cb8)

**Comment by PWDevelop** [comment]
so basically you should insert ip: 192.168.001.036 as an Ip and 8889 or 8888 as port and that should be enough.
If it was added to devices but somehow was disabled (like for me) then go to settings -> devices & services -> devices (selected from top menu) and then filter on disabled devices. Then just select device and turn it on. hopefully it's just this.

**Comment by BenPru** [comment]
Please don't use leading zeros:
192.168.1.36

**Comment by aaronlutin** [comment]
> so basically you should insert ip: 192.168.001.036 as an Ip and 8889 or 8888 as port and that should be enough. If it was added to devices but somehow was disabled (like for me) then go to settings -> devices & services -> devices (selected from top menu) and then filter on disabled devices. Then just select device and turn it on. hopefully it's just this.

![image](https://github.com/user-attachments/assets/6ef83c78-7c70-46a5-8876-60b9c00ec91c)

are al these settings correct ?

**Comment by aaronlutin** [comment]
problem solved :-p. It proves i'm a noob. The diagnose button was off because i thought i wasn't necessary. 
![image](https://github.com/user-attachments/assets/7cceae59-d196-479b-9ded-b37c861dfb94)

**Comment by aaronlutin** [comment]
Thank you for the help guys !
