### ISSUE TITLE
Firmware available notification incorrect. [Luxtronik 2024.09.30]

### ISSUE THREAD

**Issue by dmutsaers** [BenPru/luxtronik#297]
The firmware notification checks the incorrect value and creates a false positive multiple times.

Home assistant:
![Snipaste_2024-11-15_06-16-54](https://github.com/user-attachments/assets/ac826d42-d5dd-4bf3-a5d8-2288a839ffc5)

Luxtronik:
![Snipaste_2024-11-15_06-22-44](https://github.com/user-attachments/assets/135b2f2e-766c-4997-b5b8-e6a9d51fe0f1)

**Comment by BenPru** [comment]
@dmutsaers Please try the new beta [2024.11.15-Beta](https://github.com/BenPru/luxtronik/releases/tag/2024.11.15-Beta)

**Comment by dmutsaers** [comment]
@BenPru It looks like the fix solves the problem. After installing the latest beta the firmware warning disappears

**Comment by BenPru** [comment]
@dmutsaers Great. Thanks for your issue and test. I close the issue but if you see something wrong feel free to reopen it.

**Comment by dmutsaers** [comment]
@BenPru Thanks for the quick fix. I've updated my earlier post with a screenshot that shows the correct firmware version.
