### ISSUE TITLE
Missing a lot of sensors

### ISSUE THREAD

**Issue by ChrisMisker** [BenPru/luxtronik#299]
I installed firmware 3.90.2 yesterday on my Alpha Innotec, and now I wish I hadn't. I'm currently missing a lot of sensors that I used to have (I had like around 100 entities, now I only have 56). I have downgraded my firmware to 3.90.1, I have reinstalled numerous versions of Luxtronik2, rebooted, restarted, deleted everything, re-added the heat pump... I tried everything, but I'm not getting it to work. 

I think it has something to do with these error messages:
```
This error originated from a custom integration.

Logger: custom_components.luxtronik2
Source: helpers/update_coordinator.py:382
integration: Luxtronik
First occurred: 06:55:40 (8 occurrences)
Last logged: 06:57:40

Unexpected error fetching luxtronik2 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/coordinator.py", line 99, in _async_update_data
    self.data = await self._async_read_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/coordinator.py", line 103, in _async_read_data
    return await self._async_read_or_write(False, None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/coordinator.py", line 126, in _async_read_or_write
    self.async_set_updated_data(data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/config/custom_components/luxtronik2/sensor.py", line 510, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 638, in state
    raise ValueError(
ValueError: Sensor sensor.luxtronik_330123_0145_switchoff_reason provides state value '25', which is not in the list of options provided
```

Any help would be greatly appreciated, because now my house is getting cold! (I have a lot of optimisations in home assistant to get a high SCOP and a warm house.)

And no, it isn't that I have hidden entities... I'm just missing entities, such as DHW Hysteresis, the heating switch, heating curves, etc.

**Comment by kujalmi** [comment]
Same issue here...

**Comment by kujalmi** [comment]
> > Same issue here...
> 
> @kujalmi Ah, yes, it sucks! Did you also upgrade to the new firmware? Or did something else? Might help with finding out where the problem is.

Yes, upgraded to 3.90.2 and after realizing lot of sensors missing tried to load latest beta from this software but sensors still appear missing.

**Comment by ChrisMisker** [comment]
I'm on 3.90.1 now, and on the latest luxtronik beta. I'll check in a bit and do some restarts to see if that did something.

**Comment by ChrisMisker** [comment]
Quick fix! In const.py, after line number 228, add this:
```
    undefined_25: Final = 25  # ???
```
It seems they've added a new Switch off reason, which was unknown by the Luxtronik integration.

**Comment by ChrisMisker** [comment]
I'm on 3.90.2 again, by the way, all is fine. :)

I won't close this, because @BenPru has to add the above line (and perhaps others) to the release, and then he can close this.

**Comment by stefanovich1** [comment]
OK I got it.
I made a debug file and within this debug file my Integration is reffering to swith off reason 24:
ValueError: Sensor sensor.luxtronik_330123_0145_switchoff_reason provides state value '24', which is not in the list of options provided

So I added both switch off reasons --> now I got my entities back.
![image](https://github.com/user-attachments/assets/fd02feda-e771-4beb-ad14-d7a4343937e3)

**Comment by gerw** [comment]
For the record: The switch off reason 25 has been around for quite some time. It is already fixed / provided in Bouni/python-luxtronik, see https://github.com/Bouni/python-luxtronik/pull/186

**Comment by BenPru** [comment]
Please try the Main Branch. I added a quick fix.

**Comment by blue-bean** [comment]
> Quick fix! In const.py, after line number 228, add this:
> 
> ```
>     undefined_25: Final = 25  # ???
> ```
> 
> It seems they've added a new Switch off reason, which was unknown by the Luxtronik integration. You can add this yourself (custom_components/luxtronik2) and then reboot.

This solved it for me, tanks!

**Comment by ChrisMisker** [comment]
> Please try the Main Branch. I added a quick fix.

@BenPru Yes, main branch version works for me.
