### ISSUE TITLE
Sensor: Current Power needed

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#30]
Hi!

Can we have the sensor that displays "current power" usage of heat pump? It is found under:

Einstellungen --> Informationen --> Anlagenstatus --> "Leistung Ist"

Cannot not see this yet, but need it, to calculate current COP.

**Comment by Kars-de-Jong** [comment]
Yes, good idea. It is `calculations.Heat_Output`.
May not be present in all firmware versions, or supported by all heat pumps though.

**Comment by Crashman1983** [comment]
Thx! Current electrical power is measured and available in HomeAssistant :-)

I would build a template sensor and calculate current COP.

Daily COP and average COP can already be calculated using heat amount sensor. Only current missing.

Von meinem iPhone gesendet

Am 20.11.2022 um 19:50 schrieb Kars de Jong ***@***.***>:

﻿

Yes, good idea. It is calculations.Heat_Output.
May not be present in all firmware versions, or supported by all heat pumps though.

**Comment by Crashman1983** [comment]
added the sensor myself, seems to be working. I will open a pull request after some testing.

**Comment by Crashman1983** [comment]
Pull request done!

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/4194672/203039001-53617ba3-5e50-405f-b2e4-af43e0f639a7.png">

**Comment by Kars-de-Jong** [comment]
Review done!

**Comment by BenPru** [comment]
Can we close this ticket?
