### ISSUE TITLE
Software update

### ISSUE THREAD

**Issue by MichaelS1955** [BenPru/luxtronik#303]
Hi,
 when I get the information that there is a new update for the heatpump

![image](https://github.com/user-attachments/assets/57b03bb7-848b-4937-b2cf-62d712d3be07)

 I will be redirected the this internet address:
 https://www.heatpump24.com/DownloadArea.php?layout=**0**
But here I don't find my heatpump.
Could you change the link to: 
 https://www.heatpump24.com/DownloadArea.php?layout=**2**
With this layout much more heatpumps are visible

Regards
Michael

**Comment by MichaelS1955** [comment]
@BenPru I have a Novelan SICV 9.2 H3

**Comment by BenPru** [comment]
Please try the main branch. Should be fixed.
