### ISSUE TITLE
BW Soll - luxtronik_260621_0275_dhw_target_temperature - not updating

### ISSUE THREAD

**Issue by IllegalDuke** [BenPru/luxtronik#308]
Hello,

my heatpump from Alpha Innotec is connected to my PV Inverter by the use of the two digital Inputs IN5 and IN6 of the pump.
That means by changing the IN5 and IN6 by an actuator, the heat pump will be controlled to `reduced` `normal` `EVU` `increased` state.
By going into `increased` state, the hot water (BWS Soll) will be automaticaly increased by the heatpump to an higher value to load more PV-energy in the boiler.

But I recognized, that this luxtronik adapter is not updating the `BW Soll` `luxtronik_260621_0275_dhw_target_temperature` value.

I added the Bouni luxtronik interface and added the sensor `ID_WEB_Einst_BWS_akt`. There the increased water temperature is shown quickly after change.

Why is the `BW Soll` not updated? Is it just not frequently enough - just once per day?

Thank you!

[config_entry-luxtronik2-01JFD9P42N3RZ7BZ66Q8HHC7ZY.json](https://github.com/user-attachments/files/18267842/config_entry-luxtronik2-01JFD9P42N3RZ7BZ66Q8HHC7ZY.json)

**Comment by blue-bean** [comment]
Have a look [here](https://github.com/BenPru/luxtronik/issues/280).

**Comment by IllegalDuke** [comment]
Thank you, now I understood the problem... this HA integration uses the wrong ID_Web.
I will switch to the other issue and close this one.
