### ISSUE TITLE
Would it be possible to add ID_WEB_Zaehler_BetrZeitZWE1

### ISSUE THREAD

**Issue by patrickse** [BenPru/luxtronik#31]
The "old" integration offered the value of ID_WEB_Zaehler_BetrZeitZWE1 as a sensor. This sensor has shown the amount of time the heating rod was active. Was nice to see.. how often it spins up and how it develops during the heating season.

Would it be possible to add it to this integration?

**Comment by Kars-de-Jong** [comment]
Maybe also add `parameters. ID_Waermemenge_ZWE`, this is the total heat produced by the second heat source in kWh * 10 (so it needs to be divided by 10 to get kWh).

**Comment by rhammen** [comment]
To which device must this be added?
Heating, Domestic Water, or the Heatpump?

**Comment by Kars-de-Jong** [comment]
I'd say the heat pump, since it can be used for domestic water and the heating circuit.

**Comment by patrickse** [comment]
Both parameters should be added to the heatpump.

**Comment by BenPru** [comment]
See 2022.11.23
