### ISSUE TITLE
Integration lacks icons

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#32]
The integration lacks icons in the HomeAssistant Brands area:
https://github.com/home-assistant/brands#readme
A luxtronik2 folder should be created in the custom_integrations folder.
Maybe we can copy the icons from the luxtronik folder?

**Comment by scaronni** [comment]
Can't we instead just instead finishing the rename to luxtronik? The original one is not really going anywhere.

https://github.com/BenPru/luxtronik/issues/7
https://github.com/home-assistant/core/pull/59788

I'm renaming it in a local branch for my personal usage.

**Comment by scaronni** [comment]
But nothing prevents this integration (can't say enough thanks) to be renamed from `luxtronik2` to `luxtronik`, right?

**Comment by scaronni** [comment]
Then the icons would be just there...

**Comment by BenPru** [comment]
> @scaronni  But nothing prevents this integration (can't say enough thanks) to be renamed from `luxtronik2` to `luxtronik`, right?

A new try to publish this as core integration:
https://github.com/home-assistant/core/pull/86636
