### ISSUE TITLE
climate.luxtronik2_domestic_water show operation while defrosting

### ISSUE THREAD

**Issue by augi** [BenPru/luxtronik#37]
Hi, it looks like the `climate.luxtronik2_domestic_water` shows operational status when the heat pump is defrosting.

![image](https://user-images.githubusercontent.com/273052/203366455-6515de83-f0e1-48de-b938-ed11f146c1e5.png)
![image](https://user-images.githubusercontent.com/273052/203366524-6a13f1fb-d93d-4bd1-b2d5-812a5a090965.png)

Maybe we should remove `LUX_STATUS_DEFROST` from [this line](https://github.com/BenPru/luxtronik/blob/main/custom_components/luxtronik/climate.py#L234) 🤔

**Comment by BenPru** [comment]
If the heat pump runs longer when the outside temperature is low, it will defrost again and again. However, this does not end the process of heating the water or heating.
So I think a service domestic water progress should also be displayed during defrost.

**Comment by augi** [comment]
But look at the image - there are bars even when the heat pump is not preparing the domestic water. There is a defrost but as part of heating.

**Comment by BenPru** [comment]
Okay, that means both thermostats has _attr_hvac_mode != HVAC_MODE_OFF.
The last operation was heating or domestic water and then the operation changes to defrost both thermostats shows a progress?
Then we have to cache the last luxtronik state to show the correct hvac_state in the thermostat...

**Comment by augi** [comment]
Yes, it looks like that, so caching would be required if you want to keep heating/domestic water while actually defrosting.

**Comment by augi** [comment]
I can confirm the behavior now. There was defrosting during heating and:
* `Heating heating` is without any interruption, so `heating` was marked as operating during defrosting. This is OK for me although technically incorrect.
* `Domestic water heating` was marked as operating during the defrosting. This is definitely wrong.

Hope this helps with the issue resolving 🙏

**Comment by Kars-de-Jong** [comment]
I also noticed that when the heat pump is running for domestic water, it also shows as "active" in the heating thermostat graph.

**Comment by rhammen** [comment]
> I also noticed that when the heat pump is running for domestic water, it also shows as "active" in the heating thermostat graph.

Have a look at the graph below, is this where you observe the problem?
If I understand your observation correctly, I don't see this behavior: heating is only shown when the heatpump status is heating, and not when status = domestic water.

![Screenshot 2022-11-23 at 23-26-14 History – Home Assistant](https://user-images.githubusercontent.com/75572839/203656499-6aa35ab9-7434-4023-bb4b-1a26f0c8bdc7.png)

Can you create a similar graph, and/or given some other information that could help to understand why you observe this and I don't?

**Comment by augi** [comment]
You are sharing a screenshot from `climate.luxtronik2_heating` but I'm sharing screenshot from `climate.luxtronik2_domestic_water`.
![image](https://user-images.githubusercontent.com/273052/203658263-727875fc-fd7d-4994-9c2e-5214a6556df2.png)
What I'm reporting are the thin orange bars that should be there. The occurrence correlates with defrosting.

**Comment by augi** [comment]
What is also IMHO technically incorrect is that the orange value is reporting heating while defrosting is in progress. I would expect a short gap there.
![image](https://user-images.githubusercontent.com/273052/203658816-e087c09c-4266-4241-81d8-60b9ddf318ba.png)

**Comment by rhammen** [comment]
> You are sharing a screenshot from `climate.luxtronik2_heating` but I'm sharing screenshot from `climate.luxtronik2_domestic_water`. ![image](https://user-images.githubusercontent.com/273052/203658263-727875fc-fd7d-4994-9c2e-5214a6556df2.png) What I'm reporting are the thin orange bars that should be there. The occurrence correlates with defrosting.

I understood that 😃 
My remark was not about the "defrosting problem". 
My remark was about this comment by @Kars-de-Jong : "I also noticed that when the heat pump is running for domestic water, it also shows as "active" in the heating thermostat graph."

**Comment by Kars-de-Jong** [comment]
I’m not seeing my issue anymore with version 2022.12.03.

**Comment by augi** [comment]
I can still see the status of domestic water being reported when defrosting.

**Comment by BenPru** [comment]
> I can still see the status of domestic water being reported when defrosting. ![Screenshot_20221204_090927_Home Assistant](https://user-images.githubusercontent.com/273052/205480749-0e8e429c-3d83-475a-836a-7af7a09bd926.jpg)

So far this has not been fixed.
I have now included a change as a potential solution and provided it as pre-release [2022.12.04](https://github.com/BenPru/luxtronik/releases/tag/2022.12.04). You're welcome to test it.

**Comment by augi** [comment]
Hi, I can confirm it fixed my issue, thanks! 👍
