### ISSUE TITLE
Provide a sensor for "next evu event"

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#38]
A minutes timer number or timestamp with the next evu event.
If the evu is active its the time when the evu ends.
If the evu is not active its the time when the next evu starts.
For example my evu time slots are:
- 10:43-12:46
- 16:42-18:44

Example values:
- At 10:00 the value is 43 minutes.
- At 11:00 the value is 106 minutes.
- At 13:00 the value is 222 minutes.

**Comment by Gifford47** [comment]
in my case, the evu is only applicable on monday till friday. but the EVU attributes (especially "time until next evu event") is also count on sunday and saturday. is it possible to add a day related evu state?
