### ISSUE TITLE
Warning: Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#39]
2022-11-23 21:50:51.926 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for luxtronik2 doing blocking calls at custom_components/luxtronik2/luxtronik_device.py, line 151: time.sleep(3)

**Comment by BenPru** [comment]
The option "update_immediately_after_write" is not working and currently not used. So this is not really a problem.
Has anyone an idea how to perform a direct sensor update after write action?

**Comment by Kars-de-Jong** [comment]
It is used though, otherwise you wouldn't get this message.
It is set to `True` in several places, in calls to `write`.

**Comment by Kars-de-Jong** [comment]
You just have to move the wait & read to a separate thread I think.

**Comment by Kars-de-Jong** [comment]
Hmm, I see the entities themselves aren't async friendly yet.

**Comment by BenPru** [comment]
Should be fixed with the [new integration](https://github.com/BenPru/luxtronik/tree/core-preview).

**Comment by rhammen** [comment]
This issue is closed as "will be solved with the new integration", but I do still get this error with 2023.10.12 Beta:

> Logger: homeassistant.util.async_
> Source: util/async_.py:137
> First occurred: 11:05:43 PM (8 occurrences)
> Last logged: 11:07:54 PM
> 
> Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for luxtronik2 doing blocking calls at custom_components/luxtronik2/lux_helper.py, line 252: time.sleep(WAIT_TIME_WRITE_PARAMETER)

**Comment by BenPru** [comment]
> This issue is closed as "will be solved with the new integration", but I do still get this error with 2023.10.12 Beta:

This is part of the underlying package: https://github.com/Bouni/python-luxtronik
But I'm waiting for a new pypi release: [#136](https://github.com/Bouni/python-luxtronik/issues/136)
