### ISSUE TITLE
Write / update delay

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#48]
If you change a setting, the new value is immediately written to Luxtronik, but the old one is still displayed in the ha interface until the next update (~60 Sec.).

**Comment by Kars-de-Jong** [comment]
Maybe a so called "optimistic" concept could be implemented (similar to Zigbee2MQTT):

> Publish optimistic state after set, e.g. when a brightness change command succeeds Zigbee2MQTT assumes the brightness of the device changed and will publish this (default true).

So when the `write()` call succeeds, you may assume the update was actually done, and update the HA state of the entity to the new state.

**Comment by kbabioch** [comment]
> So when the `write()` call succeeds, you may assume the update was actually done, and update the HA state of the entity to the new state.

How would you know that the write succeeded? AFAIK we don't get any feedback from the controller.

I guess @BenPru has solved this in another way in https://github.com/BenPru/python-luxtronik/tree/Optimizing-data-reques by re-reading in all data after a write. Sounds like a better approach, so once merged, this issue could be closed?

@BenPru Any plans when you will create a merge request for this? Is anything essential still missing? Or do you want to give it some more time to test it?

**Comment by BenPru** [comment]
> How would you know that the write succeeded? AFAIK we don't get any feedback from the controller.

Yes. So far, the heat pump has accepted all values. For example, if a network error occurs, then I get an exception and forward it up. I haven't tested invalid values ​​(e.g. max. 180 --> 181) yet.

> Sounds like a better approach, so once merged, this issue could be closed?

Yes.

> @BenPru Any plans when you will create a merge request for this? Is anything essential still missing? Or do you want to give it some more time to test it?

Very good question. I'm currently handling 3 version repos. core-1 clone with only one sensor domain to create the first pr. core1 with all sensors for tests and this repo.
I think I try the following steps:

1. Finalize the new version with all sensors for my local tests.
2. Finalize and push core-1 with one sensor domain
3. Copy my new version to a branch in this repo and provide it as pre-release for beta user tests.

**Comment by BenPru** [comment]
Should be fixed with the new, upcoming [python-luxtronik](https://github.com/Bouni/python-luxtronik/issues) version and the [new integration](https://github.com/BenPru/luxtronik/tree/core-preview).
