### ISSUE TITLE
Wrong heating info in 2022.12.16

### ISSUE THREAD

**Issue by augi** [BenPru/luxtronik#51]
I updated to the latest version in the afternoon, and as you can see the orange value is missing for hot water, and it is still present for heating. 
![Screenshot_20221215_221022_Home Assistant](https://user-images.githubusercontent.com/273052/207968447-5d9d5240-4e98-4480-8d69-37c09be28e78.jpg)

**Comment by BenPru** [comment]
The calculation of hvac_action has changed. But I'm confused about your graph.
We can see that the water temperatures rises at 4:30 PM from 44 C° to 53 C° in one second. How is it possible?
Is it a communication problem from ha to luxtronik? Or was the water heated by solar?
The heating graph shows that the heatpump action at 4:30 PM is "heating" and not "domestic water". So I think this is correct.

**Comment by augi** [comment]
This is the first time I can see this anomaly in the water (heated in one second) so I guess it us also related to the integration update.

**Comment by augi** [comment]
Unfortunately, the heating graph is definitely wrong 😔 There should be gaps in the orange.

**Comment by augi** [comment]
Please note I originally updated from 03 to 16. I've just tried to downgrade to 14 and at least the orange bars look OK with this version.

**Comment by AJediIAm** [comment]
To me, it appears to be a problem with the update frequency. I used to have the luxtronic system time as a sensor to track the update frequency.

**Comment by augi** [comment]
Do you mean a problem on my side? Because after downgrading to 14, all looks good 🤔

**Comment by Kars-de-Jong** [comment]
When I look at the water graph it indeed seems there are periods where you don't get updated values, which causes the horizontal parts, and then a big step when a new value is read.

**Comment by augi** [comment]
Please don't focus on the steps, they are OK, they are caused by when my external water circulation pump runs.

Then problem I wanted to report in this issue is the missing orange bars in the Water, and never-ending orange bar in Heating.

**Comment by BenPru** [comment]
Please try the current pre-release [2012.12.16a](https://github.com/BenPru/luxtronik/releases/tag/2012.12.16a)
I think I have fixed it.

**Comment by augi** [comment]
Unfortunately, this version seems to be broken.
```
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 10:10:49 PM (1 occurrences)
Last logged: 10:10:49 PM

Setup failed for custom integration luxtronik2: Unable to import component: Exception importing custom_components.luxtronik2
```

```
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 10:10:49 PM (1 occurrences)
Last logged: 10:10:49 PM

Setup failed for custom integration luxtronik2: Unable to import component: Exception importing custom_components.luxtronik2
```

**Comment by augi** [comment]
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/luxtronik2/const.py:560
Integration: Luxtronik
First occurred: 10:10:49 PM (1 occurrences)
Last logged: 10:10:49 PM

Unexpected exception importing component custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 11, in <module>
    from .const import (
  File "/config/custom_components/luxtronik2/const.py", line 560, in <module>
    CONF_FREQUENCY: DEVICE_CLASS_FREQUENCY,
NameError: name 'DEVICE_CLASS_FREQUENCY' is not defined
```

**Comment by BenPru** [comment]
Sorry, to many different installations. Try 2022.12.17

**Comment by augi** [comment]
The 2022.12.17 version fixed that, thank you! 👍
