### ISSUE TITLE
Target temperature does not always update

### ISSUE THREAD

**Issue by AJediIAm** [BenPru/luxtronik#54]
I have an automation which updates "domestic water" and "heating". The automation seems to run, but the values do not get updates 2 out of 3 times.

When the domestic target temperature is set to 45, the following automation does not always update the value to 50
`device_id: 8c635edbff41e8559ceca2a0000a5bc4
domain: number
entity_id: number.luxtronik2_domestic_water_target_temperature
type: set_value
value: 50
alias: Set domestic water to 50
`

and similar for the heating target which I want to change from 0 to 1.

`device_id: 92612039a820eb13ef106a1c263a19c3
domain: number
entity_id: number.luxtronik2_heating_target_correction
type: set_value
value: 1
alias: Set Heating to 1
`

Can someone confirm this issue or is it something local?

**Comment by BenPru** [comment]
Please provide your automation as yaml here. Thank you.

**Comment by Kars-de-Jong** [comment]
I tried it twice for the first one, it immediately changed the setting (I verified it using the Luxtronik web interface), but it took a while before HA report the change back:

```
SWW gewenste temperatuur  gewijzigd in 58,0
19:26:00 - 3 minuten geleden

Nieuwe automatisering triggered getriggerd door service automation.trigger
19:25:42 - 3 minuten geleden - Tracering weergeven

Nieuwe automatisering  is ingeschakeld
19:25:38 - 3 minuten geleden

Nieuwe automatisering  is niet meer beschikbaar
19:25:38 - 3 minuten geleden

SWW gewenste temperatuur  gewijzigd in 50,0
19:22:00 - 7 minuten geleden

Nieuwe automatisering triggered getriggerd door service automation.trigger
19:21:23 - 7 minuten geleden - Tracering weergeven
```

This is because reading back the updated value is done on the regular update schedule.

Maybe a so called "optimistic" concept could be implemented (similar to Zigbee2MQTT):

> Publish optimistic state after set, e.g. when a brightness change command succeeds Zigbee2MQTT assumes the brightness of the device changed and will publish this (default true).

So when the `write()` call succeeds, you may assume the update was actually done.

**Comment by BenPru** [comment]
> This is because reading back the updated value is done on the regular update schedule.
> 
> @BenPru Maybe a so called "optimistic" concept could be implemented (similar to Zigbee2MQTT):
> 
> > Publish optimistic state after set, e.g. when a brightness change command succeeds Zigbee2MQTT assumes the brightness of the device changed and will publish this (default true).
> 
> So when the `write()` call succeeds, you may assume the update was actually done.
> 

Yes, I know. In the past I have tried many things to update faster... But I did not find a solution. See the other Ticket.
But in this ticket it sounds like a Problem writing the value, not updating.

**Comment by AJediIAm** [comment]
I did not have this issue when I used the integration from Bouni, but it does not have such fancy sensors. statement made me realize that I did not think to run both integrations in parallel to check if the change came through or what the effect is when the change is triggered through the Bouni luxtronik integration. 

I hope to give this a try this weekend.

**Comment by AJediIAm** [comment]
After some fiddling around, the whole thing seems to update better. Perhaps I made a typo somewhere...
I still like to do a bit more research on this. 
One thing I'm missing is the Luxtronik Key of the "target correction" entity. Somehow I cannot find it. Does anyone know?

**Comment by BenPru** [comment]
The luxtronik key for "target correction" is "parameters.ID_Einst_WK_akt".
By the way: You can found the underlying luxtronik key in the attribute "Luxtronik key" in every sensor:
![image](https://user-images.githubusercontent.com/32298537/208324325-d9f2c969-b4d9-4f6e-8e12-3d1ec7b77528.png)

**Comment by BenPru** [comment]
> After some fiddling around, the whole thing seems to update better. Perhaps I made a typo somewhere... I still like to do a bit more research on this. One thing I'm missing is the Luxtronik Key of the "target correction" entity. Somehow I cannot find it. Does anyone know?

@AJediIAm  Can we close this issue?

**Comment by AJediIAm** [comment]
My temperatures are still not updating correctly, but if I'm the only one it is probably something in my automation.

**Comment by AJediIAm** [comment]
Seems to be a unique issue
