### ISSUE TITLE
Luxtronik1 support

### ISSUE THREAD

**Issue by optimismus** [BenPru/luxtronik#60]
Hello @BenPru , I am quite new to HA. I own a Alpha Innoctec heatpump (about 14 years old), which has an Luxtronik 1 controller. You can find a module for iobroker https://github.com/iobroker-community-adapters/ioBroker.luxtronik1 which does the job.
As far as I can see, this module only supports luxtronik 2 - which has an LAN-Interface and not only an serial - right?
It would be a pleasure to provide all information you need to support Luxtronik 1 with your module in HA.

kind regards
axel

p.s. located in Kempen, just around the corner :-)

**Comment by BenPru** [comment]
I'm afraid that would go beyond the scope and would be a complete new development. For the base communication to Luxtronik 2 I use the project [https://github.com/Bouni/python-luxtronik](python-luxtronik) from bouni. If someone provides a module `python-luxtronik1` with same structure it would be easy for me to integrate Luxtronik 1.

**Comment by optimismus** [comment]
@BenPru Thank you for checking this.
