### ISSUE TITLE
heizgrenze is only configurable from 5 to 12 degrees?????

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#61]

**Comment by colognebroker** [comment]
How to change this , my threashold is 18 C

**Comment by BenPru** [comment]
Normally I look into the ait web interface and uses this min and max values.
Which min and max value can you set in your Luxtronik own web interface or in the local panel?

**Comment by colognebroker** [comment]
In web interface its possible to set 5 to 30c

**Comment by colognebroker** [comment]
imagin heating starts before 12 c , the most people have the threashold at 15-18 c

**Comment by BenPru** [comment]
@colognebroker Changed in [2023.01.04](https://github.com/BenPru/luxtronik/releases/tag/2023.01.04)

**Comment by BenPru** [comment]
I close this issue because I think its fixed. If not please feel free to reopen it.
