### ISSUE TITLE
how ca i get the "durchfluss l/h" ?

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#63]
- group: calculations
        id: ID_WEB_WMZ_Durchfluss
        friendly_name: WMZ_Durchfluss

this config in confiruration.yaml did not work

**Comment by BenPru** [comment]
I think the config is correct. Do you get an error in the log?
Is the value available in the diagnostic download and in the luxtronik web portal?
My heatpump (Novelan LAD 7) for example doesn't have this value and always reports `0`.
