### ISSUE TITLE
Warnings about some sensors with Home Assistant core 2023.1.x

### ISSUE THREAD

**Issue by Kars-de-Jong** [BenPru/luxtronik#64]
luxtronik version 2023.01.05

When restarting my system with Home Assistant core 2023.1.x, I get the following warnings:
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:980 
Integration: Sensor (documentation, issues) 
First occurred: 12:29:08 (5 occurrences) 
Last logged: 12:30:01

Entity sensor.luxtronik2_overheating_temperature (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'K' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.luxtronik2_high_pressure (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'bar' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.luxtronik2_low_pressure (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'bar' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.luxtronik2_pump_frequency (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'Hz' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by SvenJachalke** [comment]
I don't know if this is related to the first post (and I'm really no export, just a simple user :)) ... since I updated to HA Core 2023.1 and the last stable release of the luxtronik integration the logging of all entities stopped working (temperatures stay the same for hours, ...). I could get it working again with the luxtronik 2022.12.14 (stable) release ... after that, every (stable) release does not work (at least for me).

If I could help any further here, please let me know! I really appreciate the work here and the progress this integrations makes!

**Comment by BenPru** [comment]
> Entity `sensor.luxtronik2_overheating_temperature` native unit of measurement `K` - device class (`temperature`)
> Entity `sensor.luxtronik2_high_pressure` native unit of measurement `bar` device class (`temperature`)
> Entity `sensor.luxtronik2_low_pressure` native unit of measurement `bar` device class (`temperature`)
> Entity `sensor.luxtronik2_pump_frequency` native unit of measurement `Hz` device class (`temperature`)

@Kars-de-Jong Thanks for your ticket. I correct high_pressure, low_pressure and pump_frequency.
Do you know which device class is used for Kelvin (K)?

**Comment by BenPru** [comment]
I think its fixed with [2023.01.15](https://github.com/BenPru/luxtronik/releases/tag/2023.01.15)

**Comment by Kars-de-Jong** [comment]
> > Entity `sensor.luxtronik2_overheating_temperature` native unit of measurement `K` - device class (`temperature`)

> Do you know which device class is used for Kelvin (K)?

I don’t think there is one at this time, so that would be `None` I guess.

**Comment by BenPru** [comment]
> luxtronik2_overheating_temperature

Comes with next version.
