### ISSUE TITLE
Problem data logging >luxtronik 2022.12.14 with ha 2023.1

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#65]
Move two comments to own issue.

> Since yesterday, Home Assistant has stopped recording data.  The data is only retrieved once after a restart. 

_Originally posted by @marcelhen in https://github.com/BenPru/luxtronik/issues/62#issuecomment-1379857119_
            
> since I updated to HA Core 2023.1 and the last stable release of the luxtronik integration the logging of all entities stopped working (temperatures stay the same for hours, ...). I could get it working again with the luxtronik 2022.12.14 (stable) release ... after that, every (stable) release does not work (at least for me).

_Originally posted by @SvenJachalke in https://github.com/BenPru/luxtronik/issues/64#issuecomment-1383221542_

Will no new data be stored for just this sensor or for all sensors?
In case of all sensors I think your recorder database has reached a critical size.
I have the same because I wan' to store the data longer than the standard and the recorder stores every value change.
I delete every month with complicated and long running sql scripts data to store only one value for every minute.

My last changes in the pre-release was to store no attribute changes from the luxtronik sensors. This save many space in the database.
Do you get luxtronik log messages in your log? Please provide it here.
Exists the problem also in the last pre-release of this integration?

**Comment by BenPru** [comment]
I think its fixed with [2023.01.15](https://github.com/BenPru/luxtronik/releases/tag/2023.01.15)

**Comment by SvenJachalke** [comment]
Thanks a lot ... now it works again!
