### ISSUE TITLE
License and naming

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#7]
@Bouni
I'm trying to push my new integration ["luxtronik2"](https://github.com/home-assistant/core/pull/59788) based on your luxtronik hacs integration.
I'm using parts of [your code](https://github.com/Bouni/luxtronik). Is this okay for you?
Would you like to named as author/codeowners in the manifest.json?

Frenk would like to use "luxtronik" as domain name. This means your hacs integration has to renamed. Is this okay for you?

**Comment by sim-san** [comment]
@BenPru 
Why is the ha core implementation merge request closed ?

https://github.com/home-assistant/core/pull/59788

**Comment by BenPru** [comment]
Because he was rejected.  The code did not meet the requirements.  I'm still trying to do a complete redesign.

**Comment by BenPru** [comment]
> @BenPru Why is the ha core implementation merge request closed ?
> 
> [home-assistant/core#59788](https://github.com/home-assistant/core/pull/59788)

A new try:
https://github.com/home-assistant/core/pull/86636
