### ISSUE TITLE
Release 2023.01.20: sensor.luxtronik2_additional_heat_generator_amount_counter is missing

### ISSUE THREAD

**Issue by Kars-de-Jong** [BenPru/luxtronik#72]
This change in release 2023.01.20 causes `sensor.luxtronik2_additional_heat_generator_amount_counter` to go missing on my system:

> Detection: Use visibility id for additional_heat_generator_amount_counter

This counter is definitely present on my system, and worked fine in the previous release.

**Comment by BenPru** [comment]
I use more and more the original luxtronik visibilities. But it seems that many heatpumps has a wrong visibility config.
I have changed the behavior in the latest pre-release [2023.01.25](https://github.com/BenPru/luxtronik/releases/tag/2023.01.25).
Only two sensors based on newer firmware are not created. All other sensors should always be created but not enabled if the luxtronik underlying visibility reports "hidden".
Currently I'm focusing on the new code base, but I try to implement those "specials":
https://github.com/BenPru/luxtronik/blob/core-preview/custom_components/luxtronik/sensor_entities_predefined.py#L278
