### ISSUE TITLE
Publish this integration as ha core integrated module

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#75]
I'm currently trying to publish this integration as ha core integration.

## Core draft
The first draft (first pull request) with only one platform "water_heater" is available here:
https://github.com/BenPru/core-1/tree/luxtronik2
The first draft with all platforms is available here:
https://github.com/BenPru/core-1/tree/luxtronik

## Core draft all platforms - as custom component integration
The full integration with all platforms (but currently not the full functionality - not all sensors) as draft is available here:
https://github.com/BenPru/luxtronik/tree/core-preview

Todos:
- [ ] discover over dhcp
- [x] add sensor: error_reason
- [ ] add sensor: switchoff_reason
- [x] status sensor: add special case detection
- [x] domestic_water_thermal_desinfection_target attr: Last thermal desinfection
- [x] flow_out_temperature_target attr: Switch gap
- [x] test: sensor _restore_value
- [x] test: diag download
- [ ] test: climate.heating
- [ ] add: climate.cooling
- [x] english sensor names
- [x] add new binary sensor: id_web_asdin "ASD Abtauung wird beendet / Soledruck ausreichend"
- [x] add new binary sensor: ID_WEB_MOTin "Motorschutz OK"
-----
Important notice
Yaml configuration with own defined sensors are no more supported.
Please use [Bouni/Luxtronik](https://github.com/Bouni/luxtronik) for yaml configured sensors and ensure you don't have luxtronik2 yaml entries.

Changed sensors names:
climate.*_domestic_water --> water_heater.*_domestic_water
sensor.*_compressor_impulses --> sensor.*_compressor1_impulses

Improvements:
* Direct update of the sensor values after writing a change to luxtronik.
* Support for multiple heatpumps.

**Comment by BenPru** [comment]
@kbabioch I have created the first draft, but I have no tests. 
This are the requirements:
https://developers.home-assistant.io/docs/development_testing/#writing-tests-for-integrations
Could you help me?

**Comment by kbabioch** [comment]
Yes, happy to help. On the other hand I'm currently short on time. Not sure what your plan in regards to time is, but will definitely take me some time to have a detailed look here.

**Comment by BenPru** [comment]
> Anything specifically that you need to know or some special area where I should have a closer look?

You can review the prs:
https://github.com/home-assistant/core/pull/86636
https://github.com/home-assistant/home-assistant.io/pull/25949

I have created a very basicly test. Perhaps you can extend it:
https://github.com/BenPru/core-1/tree/luxtronik2/tests/components/luxtronik
