### ISSUE TITLE
Missing "sensor.luxtronik2.heat_source_output_temperature"?

### ISSUE THREAD

**Issue by SvenJachalke** [BenPru/luxtronik#76]
In the last version(s) the sensor "heat_source_output_temperature" (Wärmequelle Ausgang) got lost / became unavailable in my lovelace dashboard :( 
Could you reintroduce it again?
Thanks, Sven.

**Comment by Kars-de-Jong** [comment]
@SvenJachalke The sensor is still present in the integration (unless your heat pump is model LD7), but it is disabled by default. You can enable it through the integration device page, it is in the general heat pump device.

It's a pretty important measurement in my opinion, so I don't know why it is not enabled by default.

**Comment by SvenJachalke** [comment]
Thanks @Kars-de-Jong !
You are right ... it was simply deactivated :/ I agree, its pretty important ... so maybe a future version can enable it by default?

**Comment by BenPru** [comment]
Not all heatpumps supports data on this sensor. E.g. mine LAD7.
I use more and more the original luxtronik visibilities. But it seems that many heatpumps has a wrong visibility config.
But only two sensors based on newer firmware are not created. All other sensors should always be created but not enabled if the luxtronik underlying visibility reports "hidden".
Currently I'm focusing on the new code base, but I try to implement those "specials":
https://github.com/BenPru/luxtronik/blob/core-preview/custom_components/luxtronik/sensor_entities_predefined.py#L332

**Comment by SvenJachalke** [comment]
Thanks!
I see that right now its not too important (and now I know how to "fix" it) :)
