### ISSUE TITLE
pre-Release 2023.01.25 results in many (~30%?) of the sensors not being present anymore

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#79]
I encountered a serious problem when running 2023.01.25:
About 30% of the sensors where not available anymore in the luxtronik integration. 
This included most of the cooling sensors, and e.g. the domestic water target temperature number, and several pump status sensors.
I downgraded again to 2023.01.20 to resolve these problems.

Let me know if you need additional information to diagnose this.

**Comment by qubabos** [comment]
Same issue here after upgrade to 2023.01.25.
Status doesn't see any domestic water programs and idle status.
![Screenshot_20230129-131436](https://user-images.githubusercontent.com/2496350/215325531-f807f5bd-7525-4c6b-ad26-cec8e0d9de2d.png)

**Comment by Kars-de-Jong** [comment]
I really don't think that using the visibilities to determine default visibility of sensors in Home Assistant is a good idea. On my system the reported visibilities from Luxtronik don't quite match up with the actual sensors / functions that are in use, and it appears that goes for more people.

**Comment by BenPru** [comment]
> I encountered a serious problem when running 2023.01.25

I can reproduce it. I provide a fix soon.

**Comment by BenPru** [comment]
[2023.01.29](https://github.com/BenPru/luxtronik/releases/tag/2023.01.29) should fix this. Sorry for the trouble.

**Comment by rhammen** [comment]
Yes, I can confirm 2023.01.29 fixes this!

**Comment by qubabos** [comment]
mayne too ;)
