### ISSUE TITLE
luxtronik log warning

### ISSUE THREAD

**Issue by kotana** [BenPru/luxtronik#83]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:980
Integration: Sensor (documentation, issues)
First occurred: 14:07:34 (3 occurrences)
Last logged: 14:07:34

Entity sensor.luxtronik2_overheating_target_temperature (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'K' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.luxtronik2_analog_out1 (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'V' which is not a valid unit for the device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.luxtronik2_analog_out2 (<class 'custom_components.luxtronik2.sensor.LuxtronikSensor'>) is using native unit of measurement 'V' which is not a valid unit for the device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by BenPru** [comment]
@kotana Thanks for your issue.

> using native unit of measurement 'K' which is not a valid unit for the device class ('temperature')

This is wrong in the legacy ha version (I think 2022.12). Please use a newer ha version or ignore this log message.
See the current ha source:
[const > TEMPERATURE  > Unit of measurement: `°C`, `°F`, `K`](https://github.com/home-assistant/core/blob/master/homeassistant/components/sensor/const.py#L326)

> analog_out1 + analog_out2

I have changed this now. See the next release.
