### ISSUE TITLE
setup_hass_services not called for a yaml-based setup

### ISSUE THREAD

**Issue by Guzz-T** [BenPru/luxtronik#88]
With a yaml-base setup the `write` service is not registered. Home-Assistant response with `service luxtronik2.write not found`.

With the current implementation `async_setup` only calls `setup_internal` and then returns.
Adding a `await hass.async_add_executor_job(setup_hass_services, hass, conf)` afterwards should fix this problem.

**Comment by BenPru** [comment]
Which version have you installed? Is it the latest?

**Comment by Guzz-T** [comment]
Commit https://github.com/BenPru/luxtronik/commit/2947c3c65f3392693c1af4841b91242e0d93c712 with Homeassistant core installation 2022.9.7

**Comment by BenPru** [comment]
In the future release the yaml based setup is going to be disabled.
If you would like to use yaml config you can use [Bouni/luxtronik](https://github.com/Bouni/luxtronik).
