### ISSUE TITLE
How to open config again (or how to change the IP)?

### ISSUE THREAD

**Issue by 21Kingshill** [BenPru/luxtronik#93]
Sorry, if I open a potentially stupid question as issue: But can someone please help changing the IP address of the heat pump?
The IP has changed due to a restart and I cannot change the IP to another one right now.

So I need to change the IP in HA. But I do not know how.

any help is appreciated. 

Thanks,
Tom

**Comment by BenPru** [comment]
You can remove and readd the integration or you can edit the file .storage/core.config_entries (search the ip - should be in data.entries[].data.host).
