### ISSUE TITLE
Incorrect / missing translation

### ISSUE THREAD

**Issue by marcelhen** [BenPru/luxtronik#95]
Hello,

I have installed the version 2023.03.24 and so far it runs very stable.
Unfortunately, the translation into German does not work correctly.
For example:

sensor.luxtronik2_status  
sensor.luxtronik2_status_line_1
sensor.luxtronik2_status_line_2
sensor.luxtronik2_status_line_3

Are all only is in English!

Uninstalling and reinstalling did not help either. During the reinstallation, German or English could not be selected.
Can you please check this once???

Best regards

**Comment by BenPru** [comment]
sensor.luxtronik2_status, sensor.luxtronik2_status_line_1, sensor.luxtronik2_status_line_2, sensor.luxtronik2_status_line_3 are the entity ids and should never been translated. Only the "Name" is translated.
The language is detected automatically and no more asked in the setup. If the ha backend language (config > general) is german the texts are translated to german. All other cases have english names.

**Comment by marcelhen** [comment]
Hello,

It is clear that these are entity IDs, but the status is not displayed in German although the system language is German!
Attached is also the excerpt from the Config where the translation is listed. 
How can I change this?

Best regards

![Unbenannt](https://user-images.githubusercontent.com/73474450/234571392-325bb44f-1f3e-4001-8457-e88bd4a38926.jpg)
![Unbenannt-1](https://user-images.githubusercontent.com/73474450/234571417-f47d7f50-c0cf-460d-a8bb-882f316f7535.jpg)
![Unbenannt-4](https://user-images.githubusercontent.com/73474450/234571456-62e30687-724d-4583-95ed-cc4c04da4e2b.jpg)
![Unbenannt-5](https://user-images.githubusercontent.com/73474450/234571466-489df95e-33b6-4751-af24-6fffe0edd361.jpg)
