### ISSUE TITLE
Re Opening #95

### ISSUE THREAD

**Issue by marcelhen** [BenPru/luxtronik#96]
https://github.com/BenPru/luxtronik/issues/95

Hello,

It is clear that these are entity IDs, but the status is not displayed in German although the system language is German! (see pictures)
Attached is also the excerpt from the Config where the translation is listed. 
How can I change this?

Best regards

![Unbenannt](https://user-images.githubusercontent.com/73474450/234571392-325bb44f-1f3e-4001-8457-e88bd4a38926.jpg)
![Unbenannt-1](https://user-images.githubusercontent.com/73474450/234571417-f47d7f50-c0cf-460d-a8bb-882f316f7535.jpg)
![Unbenannt-4](https://user-images.githubusercontent.com/73474450/234571456-62e30687-724d-4583-95ed-cc4c04da4e2b.jpg)
![Unbenannt-5](https://user-images.githubusercontent.com/73474450/234571466-489df95e-33b6-4751-af24-6fffe0edd361.jpg)

_Originally posted by @marcelhen in https://github.com/BenPru/luxtronik/issues/95#issuecomment-1523318399_

**Comment by BenPru** [comment]
You have edited "swimming pool/solar". Please have a look in the log. Do you get any messages for "luxtronik"?
Please attach your complete sensor.de.json file in this ticket. Perhaps it has a wrong syntax.
You have reinstalled the integration, but the sensor.de.json file is not the original. Do you have a problem with the file permissions?
Which luxtronik integration version are you using? [2023.03.24](https://github.com/BenPru/luxtronik/releases/tag/2023.03.24)?

**Comment by Snapshot99** [comment]
Hello,

I have the same problem as @marcelhen .
The YAML files are unchanged for me. Luxtronik2 version is the 2023.03.24
With the HA version 2023.3.6 the translation works correctly, since the change to 2023.4.x I have the error.  

Best regards

**Comment by marcelhen** [comment]
> You have edited "swimming pool/solar". Please have a look in the log. Do you get any messages for "luxtronik"?
> Please attach your complete sensor.de.json file in this ticket. Perhaps it has a wrong syntax.
> You have reinstalled the integration, but the sensor.de.json file is not the original. Do you have a problem with the file permissions?
> Which luxtronik integration version are you using? [2023.03.24](https://github.com/BenPru/luxtronik/releases/tag/2023.03.24)?

Hello.

I use 2023.03.24 I have only changed the designation to "photovoltaic" because I operate a PV system and this runs via the swimming pool function with the comfort circuit board. This has no effect and I don't get any error messages use.

Best regards

**Comment by BenPru** [comment]
@marcelhen Is the problem still there?
If yes, please upload a diagnostic file in the ticket.

**Comment by marcelhen** [comment]
Hy @BenPru I have installed the Version “2023.9.11-Alpha-Core-Preview” and for me it works fine!!!! But I have only a problem with the outdoor temperature sensor there is no update on this!!!!

**Comment by BenPru** [comment]
> problem with the outdoor temperature sensor there is no update on this!!!!

Yes, this is also my problem. But I thougth it was only a local change problem.
But I have an idea. I try something...

**Comment by BenPru** [comment]
See 2023.9.12-Alpha-Core-Preview
