### ISSUE TITLE
additional internal heating circuits parameters

### ISSUE THREAD

**Issue by 02curls** [BenPru/luxtronik#97]
Hello, thank you for your great work. 
Since I need to automate target temperatures of the internal heating circuits, 
I would like to be able to change also the following parameters:
14: Unknown(“ID_Einst_HzMK1E_akt")
774: Unknown(“ID_Einst_HzMK3E_akt")
Would you be so kind to help with that?
thank you
Ivo
<img width="1038" alt="Screenshot 2023-04-28 at 11 09 17" src="https://user-images.githubusercontent.com/107803294/235106487-9f755799-34a6-4dba-be15-186908407158.png">

**Comment by BenPru** [comment]
Which type of heatpump do you have?
Do you know how I can detect the visibility of these values?
Please provide the following information about params 14-16 + 774-776:

- min
- max
- step
- Display name / description (english)

**Comment by 02curls** [comment]
1. I have got Alpha Innotec SWC 170H software version: V1.81.1
2. no idea, but these new value triplets are I believe 100 % analogous to curently integrated values triplet 11,12,13, so if you know how to detect the visibility of values 11, 12, 13, it should be completely the same for these analogous values. In my system, the triplet 11,12,13 defines the heating curve of the core internal heating circuit (and the accumulation tank), the next analogous triplet 14,15,16 defines the heating curve of my first floor heating circuit, and the next one 774,775,776 defines the heating curve of my second floor heating,
3. so
    11 and analogously 14, 774 (min:20 max:70 step:0,5 11name: luxtronik2_heating_circuit_curve1_temperature 14name: luxtronik2_heating_circuit2_curve1_temperature 774name: luxtronik2_heating_circuit3_curve1_temperature)
    12 and analogously 15, 775 (min:5 max:35 step:0,5 12name: luxtronik2_heating_circuit_curve2_temperature 15name: luxtronik2_heating_circuit2_curve2_temperature 775name: luxtronik2_heating_circuit3_curve2_temperature)
    13 and analogously 16, 776 (min:-15 max:10 step:0,5 13name: luxtronik2_heating_circuit_curve_night_temperature 16name: luxtronik2_heating_circuit2_curve_night_temperature 776name: luxtronik2_heating_circuit3_curve_night_temperature)

**Comment by rhammen** [comment]
Have you tried using:
Service: "Luxtronik: write"
with
Service data:
parameter: ID_Einst_HzMK1E_akt
value: <the value you need>

**Comment by rhammen** [comment]
If the problem is that you are not allowed to write to that specific parameter:
you can overrule that, but you are ON YOUR OWN!
See section on https://github.com/Bouni/python-luxtronik about writing parameters.

UNTESTED:
I would expect that if you change line 43 in /custom_components/luxtronik2/const.py to:
CONF_SAFE: Final = False
that you can write all parameters from the Luxtronik integration. 

Again: be careful, you are on your own when disabling the safeguard mechanism.

**Comment by 02curls** [comment]
I am a mere HA user, I was able to set up all integrations that I needed with the HA yamls and automations GUIs, but python is above my capabilities,

also, is what you suggested above still possible? - https://github.com/BenPru/luxtronik/issues/129

also, I believe I am not the only one with more than one heating circuit in the house, so implementing entities 14 and 774 into the integration would benefit more users?

**Comment by Kars-de-Jong** [comment]
You should probably first get these supported in https://github.com/Bouni/python-luxtronik, since they are now `Unknown` and thus do not have the correct data type and scaling.

**Comment by 02curls** [comment]
@Kars-de-Jong thank you! done that https://github.com/Bouni/python-luxtronik/pull/137 
seems OK?

**Comment by Kars-de-Jong** [comment]
Yes, looks fine, although you might as well have included the ones for mixing circuit 2 as well.

**Comment by 02curls** [comment]
@Kars-de-Jong yeah, sorry, 
got the pull request approved https://github.com/Bouni/python-luxtronik/pull/137
what can I do now to get them parameters included in BenPru's HA Luxtronic integration?
thank you

**Comment by 02curls** [comment]
@Kars-de-Jong I believe the pull request including the mixing circuit 2 parameters has been approved and merged, 
what can I do now to get them parameters included in BenPru's HA Luxtronic integration?
thank you

**Comment by Kars-de-Jong** [comment]
@02curls  You will have to wait until a new version of python-luxtronik is released which includes these changes, upgrade the requirement to at least that version and then you can use them here as well.

**Comment by BenPru** [comment]
@02curls Added to main branch. Release comes later.

**Comment by BenPru** [comment]
See [2023.10.16-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.16-Beta)

**Comment by 02curls** [comment]
tested, works, thank you!
