### ISSUE TITLE
ID_WEB_Zaehler_BetrZeitVD1

### ISSUE THREAD

**Issue by CBAMav** [BenPru/luxtronik#98]
I think there is a bug in the sensor.py.
ID_WEB_Zaehler_BetrZeitVD1 is only loaded if a VD2 is present. I think that the whole section must be something upwards
Line 299 .. 311

**Comment by BenPru** [comment]
Thanks for your hint. You are right.
Should be fixed with prerelease [2023.04.30](https://github.com/BenPru/luxtronik/releases/tag/2023.04.30)
